### ISSUE TITLE
F3 Support Component

### ISSUE THREAD

**Issue by Wolfenswan** [ferstaberinde/F3#345]
**In-Game modules:**
- Support requester
- Artillery support
- Supply drop
- Transport
- CAS strike

**All "providers" exist in two variants:**
- Virtual: no unit needs to be present in mission. If necessary (e.g. transport) will be created.
- Non-virtual: Unit needs to be present and alive in the mission. Restrictions to the unit (e.g. lack of fuel, no ammo) affect the supply requests.

**Modules allow extended modifiers:**
- Requester: # of requests per type can be limited
- Supply drop: Can modify crate init on drop.
- Transport: TBA
- CAS: TBA
- Artillery: TBA

**F3 implementation:**
* The most straightforward option would be to pre-place the modules and sync them to the aedaquate requesters (suggested: CO).
* A new component could be written or assignGear modified to allow customized supply drop contents via F3.

**Comment by ferstaberinde** [comment]
This is provisionally on the list for 3-3-0.

**Comment by ferstaberinde** [comment]
Moving to the future milestone.

**Comment by Wolfenswan** [comment]
Can't this be closed? FAXORBAT inclusion added some support modules & JTAC.

The only thing that could possibly be added is the supply drop using assignGear.

**Comment by ferstaberinde** [comment]
Closing.
