### ISSUE TITLE
F3 Spectator Script: Filter "HQ" groups created by support module

### ISSUE THREAD

**Issue by Wolfenswan** [ferstaberinde/F3#466]
Placing support modules creates "HQ" groups as well as other place-holder units for the "virtual" supports. Would be neat to filter them from the listing but not a necessity.

**Comment by ferstaberinde** [comment]
Can this be closed or moved to v3-2-3 / v3-3-0?

**Comment by headswe** [comment]
I think what i said regarding this ,was that its pointless and rather dangerous to try and filter units based on names.

**Comment by Wolfenswan** [comment]
I agree. it's a miniscule issue compared to the effort required for it.
