### ISSUE TITLE
F3 Zeus Support: Pre-place module in editor with selected Eventhandlers

### ISSUE THREAD

**Issue by Wolfenswan** [ferstaberinde/F3#484]
A curator module (possibly sinced to a playable virtual curator) could be pre-placed in the 2D-editor with some event-handlers and function-calls set up in it's initialization field.

For example:
* EH to setAISkill on newly placed units
* EH to automatically sync units between several ZEUS
* synchronize all playable units from the start

**Comment by ferstaberinde** [comment]
Can this be closed or assigned to 3-2-3 / 3-3-0?

**Comment by ferstaberinde** [comment]
Assigning this to the future for now. Unless something has crept into the v3-3-0 build, wolfenswan?

**Comment by Wolfenswan** [comment]
Closing as this has made it's way into 3-4-0 via FA Template.
