### ISSUE TITLE
Gearscript Generator

### ISSUE THREAD

**Issue by Poulern** [ferstaberinde/F3#517]
Hey guys, I'm just putting this on git although its related to the wiki. So you guys have made the briefing and debriefing generators, which work pretty well. I'm just wondering if you guys have put some thought into making something similar for the gear script, which is something that i edit for pretty much every mission i make(Usually the equipment i want is unique for each mission). For a lot of people, f3 is the first framework they encounter, and i think a page just asking for the class names, what kind of attachments, nvgs yes/no etc. Would make more people use the framework and use it better.

Oh and thanks for doing this, PA has made great use of F3 so far.

**Comment by ferstaberinde** [comment]
Closing this for now, because we'll be looking at the (optional) mk2 gear script as part of v3-3-0.
