### ISSUE TITLE
TFR Radio Channel Presets

### ISSUE THREAD

**Issue by Khaosmatic** [ferstaberinde/F3#521]
Hi,

After using F3 Framework for my communities session last week it went well besides the fact that all of our radios seem to have been on the exact same channel which involved us having to wait to solve everyone's frequency.

The way we lay it out is that we have 4 fireteams, each on a different radio frequency (5 including command) but looking through the preset scripts I cannot figure out where I would set this or even how. I still use the standard unit names like B1_AAR, etc. I was wondering if it is possible to set up a channel for Alpha 1, Alpha 2, Bravo 1 and Bravo 2.

**Comment by JonBons** [comment]
@Khaosmatic Just as a note to you, I mocked up a quick example of a possible implementation for auto-setting channel/additional channel based on F3 groups. I've yet to write code to set frequency per group but its a starting point. https://github.com/TAW-Arma/TAW-Framework.Altis/pull/5

**Comment by cptnnick** [comment]
Matthew, be aware both the ACRE2 and TFR component are being upgraded atm
and that that functionality is being planned : )
