### ISSUE TITLE
[Group Markers] DrawIcon Upgrade

### ISSUE THREAD

**Issue by Sniperhid** [ferstaberinde/F3#526]
Head has already been working on the upgrade and requested I make a ticket here with my issues.

# Group Markers (drawIcon Method)

- Needs GPS support.
- in addGroupMarker, add a check for the target entity such that if it is a string, it will check if the entity exists that the string targets, e.g.
```
_abort = false;
if(typeName _entity == "STRING") then
{
    if (isNil _entity) exitWith {_abort = true;}; 
	_entity = call compile format ["%1",_entity];
};
if (_abort) exitWith {}; 
if(isNil "_entity") exitWith {};
```
- Ensure in the init that the control event handlers for draw only getting added once, but that init can kept be calling but will just reset all markers. e.g.
```
if (isNil "f_grpMkr_handlersSet") then {
    [] spawn {
        if(isServer) then
        {
            waitUntil {!isNull (findDisplay 52)};
             ((findDisplay 52) displayctrl 51) ctrlAddEventHandler ["draw",{_this call F_fnc_drawGroupMarkers}];

        }
        else
        {
            waitUntil {!isNull (findDisplay 53)};
             ((findDisplay 53) displayctrl 51) ctrlAddEventHandler ["draw",{_this call F_fnc_drawGroupMarkers}];
        };
    };
    [] spawn {
        waitUntil {!isNull (findDisplay 12)};
        ((findDisplay 12) displayctrl 51) ctrlAddEventHandler ["draw",{_this call F_fnc_drawGroupMarkers}];
    };
    f_grpMkr_handlersSet = true; // prevent from adding agian.
};
```
- It may be a little nicer Medic icons are a bit smaller and closer to the old style marker style medic icons (small black icons). But this is just my preference do as you please :)
- I tweaked your specialist assignment to move common loop to the bottom reads a bit nicer i.e
```
_units = [];

switch (_unitfaction) do {
    case "blu_f": {
    	_units = [
    	["UnitNATO_CO_M","COM"],
    	["UnitNATO_DC_M","DCM"],
    	["UnitNATO_ASL_M","AM"],
    	["UnitNATO_BSL_M","BM"],
    	["UnitNATO_CSL_M","CM"]
    	];

    };
    case "opf_f": {
    	_units = [
    	["UnitCSAT_CO_M","COM"],
    	["UnitCSAT_DC_M","DCM"],
    	["UnitCSAT_ASL_M","AM"],
    	["UnitCSAT_BSL_M","BM"],
    	["UnitCSAT_CSL_M","CM"]
    	];
    };
    case "ind_f": {
    	_units = [
    	["UnitAAF_CO_M","COM"],
    	["UnitAAF_DC_M","DCM"],
    	["UnitAAF_ASL_M","AM"],
    	["UnitAAF_BSL_M","BM"],
    	["UnitAAF_CSL_M","CM"]
    	];
    };
    case "blu_g_f": {
    	_units = [
    	["UnitFIA_CO_M","COM"],
    	["UnitFIA_DC_M","DCM"],
    	["UnitFIA_ASL_M","AM"],
    	["UnitFIA_BSL_M","BM"],
    	["UnitFIA_CSL_M","CM"]
    	];
    };
};

{
    _style = [_x select 1] call F_fnc_getGroupMarkerStyle;
    [_x select 0, _x select 1,  _style select 0,_style select 1] call F_fnc_addGroupMarker;
} foreach _units;
```

**Comment by Wolfenswan** [comment]
@headswe @Sniperhid 

Aside from ST_automapbrigthness, are there any other issues?

If not, I'd suggest opening this up for feedback from less experienced mission-makers to decide on the user-friendliness of the new system. Depending on that feedback I'd either begin integrating or working on a legacy system to make exchanging the two systems easy.

**Comment by ferstaberinde** [comment]
Sniperhid - is it possible to close this issue now?

**Comment by Sniperhid** [comment]
This is still being worked on, been testing this at 1Tac and it's still being developed and improved (had some pesky bugs), once we have a stable, easily configurable more final build I'll PR it here but I suspect it could be ~a month we'll see.

Here are some previews of the progress to date though:
Group hierarchy marker zoom (markers converge depending on the zoom) - https://www.youtube.com/watch?v=sX-tJYQgec8

Preview New Icon set (courtesy of Bear)- https://dl.dropboxusercontent.com/u/27305806/2015-04-06_00007.jpg

**Comment by Wolfenswan** [comment]
How's the progress on this one @Sniperhid?

**Comment by Sniperhid** [comment]
DrawIcon generally looks worse than using markers unless create custom art work. I think this is out of scope for F3 for now at least unless someone else wishes to take it over.
