### ISSUE TITLE
F3 3-2-2  Documentation

### ISSUE THREAD

**Issue by Wolfenswan** [ferstaberinde/F3#544]
**README**

* Added F3 Assign Gear AI component:
 * Loops through present or selection of AI and re-equips them with corresponding F3 gear.
* Updated F3 Briefing Template component:
 * Increased font size of headlines for better readability.
* Updated F3 Folk ARPS Assign Gear Script component:
 * Loadout setting can now be over-written on a per unit-type basis.
 * Optional faction input is now always lowered.
* Updated F3 Spectator Script component: 
 * Reduced performance impact of tags.
 * Fixed issues with JIP players.
 * Fixed issue where TFR spectators sound as if they are underwater.
 * Fixed issue with script error when using TFR
 * Fixed Tag Colors
* Updated Radio Systems Support component:
 * ACRE2: Improved frequency assignment.
* Updated Medical Systems Support component:
 * SWS: various fixes.
 * AGM: improved item-converter and re-balanced item assignment.
* Updated F3 AI Skill Selector component:
 * Tweaked default skill levels: medium and low slightly better.
 * Tweaked default skillSet: non-aiming skills higher by default.
 * Merged randomUp and randomDown into one variable.
 * Improved impact on network traffic: only sets skill where unit is local
 * fn_setAISkill can now be called with only the unit as argument
* Updated F3 Zeus Support
 * fn_zeusInit automatically detects if F3 AI Skill Selector component is active and uses it on new
 units
* Updated F3 PreMount component
 * Only ignores vehicles if locked state is exactly 2
* Updated AI Caching component:
 * New variables f_var_cacheRun & f_var_cacheSleep to control component behavior from outside
 * Can now pass aggressiveness directly to f_fnc_gCache as optional param
* Fixed AI Caching component:
 * Infantry would not disable simulation properly on aggressiveness 1 and 2.
* Fixed ORBAT Notes and Name Tags components:
 * Fixed issue where the number of cargo seats in a vehicle would not be calculated correctly.
* Fixed F3 Mission Conditions Selector:
 * Default overcast values would occasionally cause rain.

**WIKI**
- [x] F3 Assign Gear AI new
- [x] F3 Assign Gear update
- [x] F3 SetAISkill update
- [x] F3 Briefing update (add Bear to credits)
- [ ] F3 Example Missions - most recent missions are 3-1-0!
- [ ] F3 Spectator Script - update screenshots?
- [ ] F3 Tutorials - update screenshots and files?
- [x] F3 Caching - detail aggressiveness settings, detail how to use it to "store" groups
- [x] F3 Radio System - update for ACRE2/TFR? @Sniperhid , @cptnnick 
- [x] F3 Medical System - update for AGM? @cptnnick

**Comment by ferstaberinde** [comment]
I've edited the README.md text - both in the OP of this issue, and in the actual file (updated in DEV branch).

**Comment by Wolfenswan** [comment]
http://ferstaberinde.com/f3/en//index.php?title=Dev_F3_Folk_ARPS_Assign_Gear_AI has been created and requires proof-reading.

**Comment by Wolfenswan** [comment]
Updated
http://ferstaberinde.com/f3/en//index.php?title=Dev_AI_Caching
to explain manual caching/restoring

Added explanation to http://ferstaberinde.com/f3/en//index.php?title=Dev_F3_Folk_ARPS_Assign_Gear_Script#Changing_backpack_loadouts
on how to overwrite loadout on a per-type basis.

**Comment by Wolfenswan** [comment]
Most of the dev pages are implemented. Open ones are mostly missing updated screenshots etc.
