### ISSUE TITLE
Player being flung into the sky.

### ISSUE THREAD

**Issue by Khaosmatic** [ferstaberinde/F3#546]
Hi there, ever since the group I have been playing with have been using F3 (me being the one scripting it however I have followed all the tutorials correctly) we have encountered an issue in some sessions which has happened twice now. What happens is a player is teleported somewhere random and just (excuse the need for a better term) spazzes out in mid air. It has happened as infantry and the other when exiting a vehicle.

Video Reference:
https://www.youtube.com/watch?v=WaChUnuHQLg

The server was running mods like AGM and TFAR but I wouldn't have thought they would be an issue. I also made sure the teleport feature was off.

**Comment by Sniperhid** [comment]
@cptnnick and myself have seen similiar things to this this before at our respective communities. The difference in what I have seen is that players were teleported really high up and left in a 40 second+ freefall, eventually hitting the ground. The main difficulty is in correctly identifying the source of the problem as it may not even be F3, we both use AGM and other mods too at our communities too. One theory we did have was that it was the Sahrani map causing it. I believe we are best served logging any information here when it does happen again providing more details on the mods/mission/circumstances around what may have caused it so we can better find the source.

If I remember correctly we asked @Wolfenswan if Folk ARPs has experienced anything like this before and if I recall correctly they haven't, but he can correct me. This is significant because Folk ARPs don't use mods which indicates this is more or a mod problem than specifically F3.

**Comment by cptnnick** [comment]
We have been experiencing slight teleportation issues, almost always on
AiA_TP maps.

**Comment by Wolfenswan** [comment]
I've never seen this happen.

**Comment by cptnnick** [comment]
There is also no code in F3 that could cause this as far as I am aware.

**Comment by Wolfenswan** [comment]
None that is always running by default at least.

**Comment by Khaosmatic** [comment]
Its a strange one, I really cant think of anything in the mission that causes it. It was also on the default ARMA terrains. To give a quick rundown of the modlist (in case it helps)

(Overhauls)
- AGM
- task_force_radio

(ShackTac Mods)
- st_gi
- st_nametags
- st_stamina_bar
- sthud_a3

(Weapons)
- sti_launchers
- sti_weapons
- RH_M4_A3
- rh_pistol_a3

(AI)
- ASR_AI3
- TPWCAS_A3

(Misc)
- TEN_fluidDoorOpening
- ASDG_JR
- L-ExShake
- L-Twitch
- mrb_a3_voicestop
- outlw_magrepack
- safety

None of them come to mind in which to cause issues, unless it is due to a script compatibility issue. In terms of F3 internals, I really have no idea to look this issue has puzzled me.

**Comment by Khaosmatic** [comment]
As much as I do hate to say it, it has only started happening since we began using F3. I do know I have the previous version of F3 but even then when that version was the standard it happened. There is a possibility that one of the people who experienced the issue might have some other mods on their collection.

Thinking about it the only major alterations I did to the default F3 (besides gear scripting) was putting it on Stratis (both missions I did this the issue was encountered) and I did it by editing the SQM. I have no idea if that could even remotely be close to what is causing the issue but trying it on Altis without swapping the mission over to Stratis might yield a result.

**Comment by cptnnick** [comment]
I normally make an F3 mission by porting over anything but the .sqm. The
platoon I merge in, in the editor. So it can't be related to that.

What coordinates do you get teleported to?

It started happening for us around the start of december, and for a few
players only.

**Comment by Wolfenswan** [comment]
Does it only happen at the beginning of missions or all throughout?

**Comment by Khaosmatic** [comment]
Thinking about it, last Friday we were in the mission for 25 minutes? Once we landed on the beach in boats when the driver got out he was teleported. The other time was also roughly the same come to think of it?

**Comment by Wolfenswan** [comment]
How many players do you have? Which F3 components did you enable/disable?

**Comment by Khaosmatic** [comment]
We ran with 16 last Friday, the performance was fine all around as far as I know, no desync occurred for the whole thing. I did mess around with teleporting but I couldn't get it to to work for all the leaders so I disabled it correctly by putting // infront of it all. Looking at the init.sqf, everything is disabled for that mission besides JIP Setup that I haven't touched (unsure how it works at the moment).

(The Init.sqf)
https://www.dropbox.com/s/dq00a454ukjdbrp/init.sqf?dl=0

**Comment by Wolfenswan** [comment]
Very strange.

Is there suspicious anything in the RPTs?

**Comment by Khaosmatic** [comment]
AGM Medical System. Looking over the RPT log, I'm not really sure what to look for. There are errors but nearly all of them are to do with sounds. I did see:

"21:58:58 Ragdoll - loading of ragdoll source "Soldier" started.
21:58:58 Ragdoll - loading of ragdoll source "Soldier" finished successfully."

Right after it involves a player rejoinging after connection issues (which happened right after the other player was teleported).

**Comment by cptnnick** [comment]
Could you please list all the AGM .pbos / parts that your group uses?

**Comment by Khaosmatic** [comment]
All of the them are enabled on all clients. The only modules on the server are the Medical Module (as I had no idea how to configure it within F3) and the Explosives System.

**Comment by Khaosmatic** [comment]
The bug strikes back, seems it happened in last nights session as well. Playercount was more or less the same however this time it was about 40 minutes in or so. This was session was on a mission played before however we did not encounter the error then.

**Comment by Khaosmatic** [comment]
So far without a change to the files, I have not noticed it the past two sessions we have had. Unless certain situations make it happen but I'm pretty sure it was due to copying the SQM. As the past 2 missions were done without doing that.

**Comment by Khaosmatic** [comment]
I think that is it issue solved.

It must have been due to copying the SQM.
