### ISSUE TITLE
Custom AI caching

### ISSUE THREAD

**Issue by Poulern** [ferstaberinde/F3#554]
I've stopped using AI caching. It simply turns the AI invisible, but they still shoot their guns/static weaponry etc. This is completely useless to me. Now at the same time i use the gearscript to give AI their gear so if i want to do a QRF i would have to have them preplaced, and since i want to keep sfps as high as possible i would like to use the AI caching, but i don't want to use it for 90% of the AI in the mission, so using the array would be a huge pain.

So my request is for something like a line to drop in the init that caches the AI, maybe with something like a customizable distance, or just a static one of 1km or whatever.

**Comment by cptnnick** [comment]
This sounds more like a bug than something that needs a new feature.

You're saying cached AI is being hidden, but their simulation still
enabled? Is it only for static vehicles or units as well?

**Comment by Poulern** [comment]
For AI as well. Try putting the caching to 800 and see AI shooting at you. I once put it to 3 meters and they shot at you invisible. Not sure if they move as well.

**Comment by headswe** [comment]
Are you using any other scripts?
A modline would be nice too.

**Comment by Poulern** [comment]
@AiA_TP
@ASDG_JR
@baf_vehicles
@Bornholm
@BWA3
@Caribou
@CBA_A3
@Dariyah
@fhq_accessories
@hlcmods
@K_MNP
@mrb_a3_voicestop
@PA_agm
@pa_chvd
@pa_l85a2
@Panthera
@RDS_STATIC
@RHSafrf
@RHSusf
@StUi
@tao_foldmap_a3
@task_force_radio
@tf47_launchers

Are the mods loaded serverside. Specifically it has happend with these mods: HLC AKs, RHS AKs, RHS Iglas, RDS Static, on takistan. Happens with and without UPSMON(No other scripts were used apart from F3)

**Comment by Wolfenswan** [comment]
I found the issue and I've got no idea how it slipped through. Caching (un)hides the units properly but doesnt disable the Sim. I remember testing the line in question and it working as intended so I guess it must have changed with one of the last stable updates and no one noticing it.

**Comment by Poulern** [comment]
Yes that would be how I would describe it. Invisible ai that have
simulation.

**Comment by Wolfenswan** [comment]
Fix here:
https://github.com/Wolfenswan/F3/commit/8bc1606d00f4ba6d49836c3e0b90651b9e64a631#diff-1

Need to test this on a dedicated environment but as locality wasn't the issue here I assume it will work fine. Just a rather puzzling script error.

**Comment by Wolfenswan** [comment]
@Poulern let me know if the fix works for you or if you spot anything else. It's possible to do what you described earlier (stashing AI and restoring them manually), just spawn the cache/uncache function directly with the groups. If you're using normal caching on the side you might also have to set the variable to ignore those groups.

**Comment by Poulern** [comment]
Might be while before I'd be able to test this again, just a heads up.

**Comment by Wolfenswan** [comment]
I'm quite confident we caught the issue. When setting caching to 5m, I'm not engaged by hidden units on aggressiveness 2-3, on setting 1 only the hidden team leader engages me.
