### ISSUE TITLE
[Issue] Mat Gunner back pack contents refuse to change.

### ISSUE THREAD

**Issue by Khaosmatic** [ferstaberinde/F3#568]
Hi, while scripting some BLUFOR units, I noticed the default LR Radio in Task Force Radio is the little one that can barely hold anything. So I am trying to find the file which defines what the LR backpack is?

Does anyone know where it is found because I cannot find it at all.

**Comment by cptnnick** [comment]
The radio is stored in a TFR variable, not an F3 one. This ensures the
default TFR radios are assigned normally, so it won't break when TFR
changes a class name.

If you want to change the assigned radios, change it some something like:
```
_radio1 = "class name";
```

**Comment by Khaosmatic** [comment]
Aha, that is what I did but without the "", hangon a sec.

**Comment by Khaosmatic** [comment]
Hmmm, I tried it, 

_radio1 = "tf_rt1523g_big";

Still not working for me.

**Comment by cptnnick** [comment]
Something on your end then, it does work for me. Are you sure the TFR
component is enabled and radio handouts aren't set to default?

**Comment by Khaosmatic** [comment]
Wait while I repeatedly bash myself in the head, REMEMBER KIDS ALWAYS CHECK YOU ARE IN THE RIGHT MISSION FOLDER.

Thanks cptnnick you are a hero for replying so fast!

**Comment by cptnnick** [comment]
: ) happened to me more often than I'd like to admit...

I'll try to document it better when I update the TFR component.

**Comment by Khaosmatic** [comment]
:D Awesomesauce my good sir.

**Comment by Khaosmatic** [comment]
If it is possible to quickly solve an issue, this time not due to being on the wrong file.

Every unit I edit the backpack contents of works, except the MAT Gunner's, checking the unit name in game as well as the assigngear name they all match up yet, none of the contents change when I alter it.

**Comment by cptnnick** [comment]
Check if units aren't carrying vanilla loadouts. If there is a mistake in
the gearfile, it fails without telling you.

**Comment by Khaosmatic** [comment]
This is the actual backpack section.

// BACKPACK: MAT GUNNER (MATG)
case "matg":
{
	// LOADOUT: LIGHT
	if (f_param_backpacks == 0) then {
		_unit addBackpack _baglarge;
		clearMagazineCargoGlobal (unitBackpack _unit);
		(unitBackpack _unit) addMagazineCargoGlobal [_MATmag1, 2];
		(unitBackpack _unit) addMagazineCargoGlobal [_MATmag2, 2];
		(unitBackpack _unit) addMagazineCargoGlobal [_carbinemag, 2];
		(unitBackpack _unit) addMagazineCargoGlobal [_grenade, 2];
		(unitBackpack _unit) addMagazineCargoGlobal [_smokegrenade, 2];
	};
	// LOADOUT: MEDIUM
	if (f_param_backpacks == 1) then {
		_unit addBackpack _baglarge;
		clearMagazineCargoGlobal (unitBackpack _unit);
		(unitBackpack _unit) addMagazineCargoGlobal [_MATmag1, 1];
		(unitBackpack _unit) addMagazineCargoGlobal [_MATmag2, 1];
		(unitBackpack _unit) addMagazineCargoGlobal [_carbinemag, 2];
		(unitBackpack _unit) addMagazineCargoGlobal [_grenade, 2];
		(unitBackpack _unit) addMagazineCargoGlobal [_smokegrenade, 2];
	};
	// LOADOUT: HEAVY
	if (f_param_backpacks == 2) then {
		_unit addBackpack _baglarge;
		clearMagazineCargoGlobal (unitBackpack _unit);
		(unitBackpack _unit) addMagazineCargoGlobal [_MATmag1, 2];
		(unitBackpack _unit) addMagazineCargoGlobal [_MATmag2, 2];
		(unitBackpack _unit) addMagazineCargoGlobal [_carbinemag, 2];
		(unitBackpack _unit) addMagazineCargoGlobal [_grenade, 2];
		(unitBackpack _unit) addMagazineCargoGlobal [_smokegrenade, 2];
	};
};

**Comment by Wolfenswan** [comment]
Can you detail your issue? Do you want MATG with TFR radios or different gear?

**Comment by Khaosmatic** [comment]
Oh no I renamed as I thought it would be a pain for you guys if I just made another post. It was just about how I cannot change the gunners backpack. It is most likely a default gear issue due to an error in the assigngear. I will double check.

**Comment by Khaosmatic** [comment]
Closing this, I think it must be an issue regarding backpack defaults under assign gear as it's working now. Thanks for the assistance.
