### ISSUE TITLE
fn_setweather overcast still causes rain

### ISSUE THREAD

**Issue by captainblaffer** [ferstaberinde/F3#574]
My suggested fix in the previous issue was incorrect. 0.55 overcast still causes rain.
Relevant issue: # 572

fn_setweather overcast causes rain

to fix change :
// Overcast (Calm)
case 3: // 4 & 5 too
{
_MissionOvercast = 0.55;

TO
_MissionOvercast = 0.49;

I tested 0.49 at least 5 times, it didn't rain this time :)

**Comment by Wolfenswan** [comment]
Thanks for testing has been updated in Dev.
