### ISSUE TITLE
Spectator Script + TFAR Functionality.

### ISSUE THREAD

**Issue by Khaosmatic** [ferstaberinde/F3#576]
An issue we have been having a while which makes spectator chat useless is the effect when talking underwater is applied in the spectator lobby. Everyone is muffled and I cannot recall if you can hear alive units clearly either.

I used the basic TFAR Spectating layout but I cannot figure out the issue, it looks fine to me?

**Comment by cptnnick** [comment]
The issue is the created virtual unit falls into the sea : D

It's fixed for the next version. In the meantime:

In f\aspect\fnCamInit.sqf, change it to look like this:
````
createCenter sideLogic;
_newGrp = createGroup sideLogic;
_newUnit = _createUnit ["VirtualCurator_F",[0,0,0],[],0,"FORM"];
_newUnit allowDamage false;
_newUnit hideObject true;
_newUnit enableSimulation false;
_newUnit setPos [0,0,5];
````

**Comment by Khaosmatic** [comment]
Aha, so does is doing that as I thought! Ok thanks I will give this a try.

**Comment by Khaosmatic** [comment]
Hmm, I don't have an 'aspect' folder?

**Comment by cptnnick** [comment]
Typo! 'spect' obviously. Auto correct strikes again.

**Comment by Wolfenswan** [comment]
Closing because issue is revolved and fixed in dev.
