### ISSUE TITLE
Restructure Wiki

### ISSUE THREAD

**Issue by Wolfenswan** [ferstaberinde/F3#577]
I am not sure if the current split into "Require configuration","Pre-configured", "Optional" and "Folk ARPS" is the preferable way to list the documentation. The Respawn settings for example do not necessarily require configuration and the Folk ARPS components seem slightly out of place at the bottom, in contrast of the importance the assign Gear component has.

The split between foundation and specific builds does not seem to apply either.

**Comment by Wolfenswan** [comment]
Suggestion for a new listing:

**Default components**
* Mission branding (name, header, loading screen)
* Assign Gear Related
 - all assign gear components
* Group Configuration Related
 - group ID
 - group markers
 - fireteam markers
* JIP & Respawn Related (Spectator etc.)
* Briefing Related
etc.

**Optional components**

**Comment by ferstaberinde** [comment]
This will actually happen before v3-2-3
