### ISSUE TITLE
[Question] JIP

### ISSUE THREAD

**Issue by Khaosmatic** [ferstaberinde/F3#580]
Hi, after a session last night I noticed an issue that I think has been the case for a while now, wherein if AI Are left open for JIP in standard fireteams sometimes players can join them and play (I think a player can join the same slot he left?) but then at other times if a player leaves for example a medic role in a different group and joins an automatic rifleman which was the case last night he was just put to a spectator screen.

We do play with no respawns on and the F3 JIP options are not active for any units as I haven't really looked into it. So does anyone know why joining a AI slot takes the player to spectator? Is it to do with the fact that, the players in mission ID or something is bound to the one character he began the mission with?

**Comment by cptnnick** [comment]
Can you list your respawn settings from description.ext please? Found in
the F3 - Respawn Settings block.

**Comment by Khaosmatic** [comment]
Righty ho, here you are:

respawn = 1;
respawndelay = 3;
respawnOnStart = 0;
respawnTemplates[] = {"f_spectator"};

**Comment by Sniperhid** [comment]
Are you positive that the slot has an AI in it, and that the AI unit was still alive? I may be on to nothing here but I suspect a dead AI unit may cause this.

**Comment by Khaosmatic** [comment]
That's the weird thing, the AI were all fine and I think it use to work but I cant be sure I think sometimes it does and doesn't dependant on if a player has already been a certain unit when the mission began then left for whatever reason and connecting to a different slot rather than the one he was in just doesn't work.

A work around I guess would be to put the JIP on every playable unit on the mission with the standard assigngear, etc?

**Comment by Wolfenswan** [comment]
You might also try the current dev build as it includes some fixes to spectator & JIP.

**Comment by Khaosmatic** [comment]
Roger, has the new version got a fixed release date as of yet?

**Comment by Wolfenswan** [comment]
Unfortunately not, as we're delayed due to RL issues. You can treat the dev branch as the RC candidate.

**Comment by Khaosmatic** [comment]
I see a new version has released, does that include the fixes the dev had?

**Comment by Wolfenswan** [comment]
Yep

**Comment by cptnnick** [comment]
Yes.
