### ISSUE TITLE
Assign Zeus to host issues

### ISSUE THREAD

**Issue by Khaosmatic** [ferstaberinde/F3#581]
After doing 2 sessions of testing on small scale with 5 players on a dedicated server, using the assign Zeus function to host under Admin has some pretty interesting issues. One of which is when selecting a units stance, behavior or speed it resets and you have to do it again, for example after hitting ok it keeps the box open and you have to enter all the information you want again which can be frustratating and take a lot of time. Also it seems to preset them a lot like the AI will always want to go prone even when out of contact.

There is also an issue where if the person playing Zeus is killed and when accessing the Zeus controls from the editor, all the units placed, etc from when using Zeus while alive are unable to be interacted with. And as you are dead you cannon get the Admin briefing page to allow all current units to be edited, etc.

Another one is the weather module not wanting to change the weather for a good 5 minutes or so which meant timeskipping had to be used.

This has all been done with the standard assign Zeus to host layout. It was on a mission already that had units.

**Comment by Wolfenswan** [comment]
> after hitting ok it keeps the box open and you have to enter all the information you want again
> Another one is the weather module not wanting to change the weather for a good 5 minutes or so which meant timeskipping had to be used.

I've seen this is as well but independent from the F3 menu. My understanding is that it's an issue in Vanilla, possibly tied to dynamically creating ZEUS. Little I can do about is as there's hardly any scripting involved on F3's side in that regard.

> There is also an issue where if the person playing Zeus is killed and when accessing the Zeus controls from the editor, all the units placed, etc from when using Zeus while alive are unable to be interacted with. And as you are dead you cannon get the Admin briefing page to allow all current units to be edited, etc.

Try the ARES addon for that. It allows you to put units under your control from the ZEUS interace.

**Comment by Khaosmatic** [comment]
Aha I see, I will look into it and put up a post on the Feedback Tracker. Thanks for the assistance.
