### ISSUE TITLE
[Question] Universal Items & Weapon Pools

### ISSUE THREAD

**Issue by Khaosmatic** [ferstaberinde/F3#586]
After redoing my loadouts on the new version I only just noticed the universal items which has to be one of the most useful parts on there! Already I have done several AGM items like map tools and defusal kits but I was wondering if there is a way to do multiples?

Like add x8 bandages, x2 morphine and x2 epinephrine for all units? Would it just be constantly repeating like

_unit linkitem "AGM_Bandage";
_unit linkitem "AGM_Bandage";
etc.

Or can you do something similar to adding multiples of items on the actual classes like:

{_unit addItem _bandage} forEach [1,2,3]; ?

**Comment by Khaosmatic** [comment]
Also, does F3 support weapon pools/random weapon assignment? Like if I made an insurgent mission and gave 10 different weapons that were possible for a unit to have to randomly assign it to that person? I have a sort of rough idea how it would work but no idea how add the appropriate ammo for that randomly selected gun.

**Comment by Sniperhid** [comment]
Firstly it isn't wise to use linkItem on AGM_Bandage, as linkItem is basically addItem and then assignItem (moving the item into the item slot like GPS/MAP slots in the inventory, and bandages don't have a special slot). Either method you suggest would work, we tend to use the second method as it is shorter to write (here I have modified to give 8 bandages):

    {_unit addItem _bandage} forEach [1,2,3,4,5,6,7,8]; 

Randomization isn't too difficult but it is possible (but I am going to assume the simple case where all the weapons use the same ammo). BIS_fnc_selectRandom is a useful function that takes an array as input and will return just one of the elements e.g. "rifle_name1";

    _rifle = ["rifle_name1","rifle_name2","rifle_name3"] call BIS_fnc_selectRandom;

**Comment by Khaosmatic** [comment]
I quickly realized the linkitem problem just after posting, but in the not so simple case is it something of great difficulty trying to detect the weapon and get its magazines within the current F3 files. I know of other scripts that do it but I fear for conflictions between F3 and the others.

**Comment by cptnnick** [comment]
````
_pool = [
[weapon1ClassName,ammo1ClassName,ammo1ClassNameTracer],
[weapon2ClassName,ammo2ClassName,ammo2ClassNameTracer]
];

_selection = _pool call BIS_fnc_selectRandom;

_rifle = _selection select 0;
_riflemag = _selection select 1;
_riflemagtr = _selection select 2;
````

This should give you a random weapon with fitting magazines. You'll have to
build the _pool array yourself.

**Comment by Khaosmatic** [comment]
Where would that go? Is it just making a class like CO and then assigning that class in the init of all units?

**Comment by cptnnick** [comment]
Ah yes sorry. This would go in the faction assignGear file where, in this
example, _rifle, _riflemag and _riflemagtr are defined. This will then set
_rifle for the player. A simple case of pasting it over the portion where
_rifle, _riflemag and _riflemagtr are defined.

Since the code is run locally for each unit or player, you don't need to
put it inside the specific unit 'cases'.

You could easily modify this code to work for any of the other weapon class
as well, like _carbine and _arifle.

If you have questions on how to do that, or how it exactly works, I'd be
glad to give an explanation!

**Comment by Khaosmatic** [comment]
I will look into it tomorrow however knowing me I probably will need that explanation! xD 

Thanks for the assistance so far though very helpful!
