### ISSUE TITLE
spectator: better view defaulting

### ISSUE THREAD

**Issue by Wolfenswan** [ferstaberinde/F3#589]
The spectator script sometimes defaults the view to [0,0,0] which seems to cause a massive drop in framerate for an unknown reason (render distance for tags? virtual agents at location?).

By defaulting the view to any (playable) unit this could probably be helped.

**Comment by headswe** [comment]
This shouldn't happen.

**Comment by Wolfenswan** [comment]
It happens when entering/exiting ZEUS from spectator script.

**Comment by ferstaberinde** [comment]
Head, has this been fixed as part of the v3-3-0 update? Assigning to the future milestone for now, but please re-assign back to 3-3-0 and close if it has been addressed. Thank you.

**Comment by headswe** [comment]
Should be okay, due some changes, not sure what we shall close it or not.

**Comment by ferstaberinde** [comment]
Okay - assigning to v3-3-0 miletsone now but re-labelling as a bug. We can close after RC1 is tested, perhaps.
