### ISSUE TITLE
Uncaching units may spawn them to high

### ISSUE THREAD

**Issue by Soldia1138** [ferstaberinde/F3#591]
In the fn_gUncache.sqf, an if-condition checks if the leader is moving in order to place cached units next to him:

if (speed leader _this > 0 && vehicle _x == _x) then {
    	_x setPosATL (formationPosition _x);
};

Unfortunately getPosATL and formationPosition got a different z-Coordinate. For some reason formationPosition always returns a value between 0 and 1 for the z-Coordinate. Therefore some units will get killed due to spawning high and hitting the ground too fast.

Suggestion: Manually set the z-Coordinate to 0:

if (speed leader _this > 0 && vehicle _x == _x) then {
    	_x setPosATL [(formationPosition _x) select 0, (formationPosition _x) select 1, 0];
};

Or make them invincible for a short period of time.

**Comment by Wolfenswan** [comment]
Good spot, thanks.

**Comment by Wolfenswan** [comment]
Merged into dev.
