### ISSUE TITLE
Play "wounded" sounds for downed players

### ISSUE THREAD

**Issue by Wolfenswan** [ferstaberinde/F3#593]
Play a looping moaning/wounded sound when players are downed. More immersive and makes locating those players easier.

Example sound:
"A3\Missions_F_EPA\data\sounds\WoundedGuyA_01.wss"

**Comment by ferstaberinde** [comment]
Is the sound one of the default game resources?

**Comment by Wolfenswan** [comment]
Yes, there are about a dozen in cfgSound

**Comment by ferstaberinde** [comment]
Before we make this part of F3, could we test it in a mission? In principle I like the idea, but I can also see how some players would find it annoying having to listen to those sounds a lot whilst waiting on the medic.

**Comment by Wolfenswan** [comment]
It's the same sounds played by the engine when the player is wounded normally.

**Comment by Wolfenswan** [comment]
Eh, apparently the game already plays sounds due to setDamage being > 0 when downed by SWS. Must have had a brainfreeze.
