### ISSUE TITLE
assignGear update for Marksman DLC

### ISSUE THREAD

**Issue by Wolfenswan** [ferstaberinde/F3#594]
Upcoming DLC adds 5 new Marksman rifles, 2 MGs and bipods, as well as a few other tidbits (uniforms etc.)

This warrants some changes to the assignGear files but also raises the question if we want to introduce DLC weapons into the default mix.

**Comment by Wolfenswan** [comment]
**Uniforms**
* new variants for existing vests, some faction-neutral (better vests for FIA)
* new ghillie suits (DLC content)

**Comment by Wolfenswan** [comment]
**Suggestions for assignGear files**
* new weapon class: _marksmanrifle
* new loadout type: "dm" - marksman (outfit like the others but with a MRCO marksman rifle)
* give FIA armored vests (new neutral black/olive ones)
* add GPS to all loadouts for balance purposes
* change ghillie suits to DLC versions (reasoning: sniper slots are rarely taken)

**Comment by ferstaberinde** [comment]
Wolfenswan - if the DLC weapons were restricted to roles that are defined in the assignGear scripts, but NOT used in the pre-placed platoons, would that cause issues for MMs that don't own the DLC?

For example, could we have two variants of the NATO MMG, one with the vanilla CSAT weapon currently use, and another (MMGG_DLC) with a DLC weapon?

**Comment by Wolfenswan** [comment]
i'd rather leave the non-dlc weapons as commented out in the assignGear files

mission-makers won't have issues (as they don't have with the helo DLC), it's just interacting with the items in-game which is restricted (accessing as crew, picking the weapon from a crate etc.)

**Comment by ferstaberinde** [comment]
Let's go with your suggestion of putting the classnames in the assignGear files but commenting them out. Assigning this to you and the 323 MS.

**Comment by Wolfenswan** [comment]
This poses the question whether the curent CSAT MMG (Zafir) should become the CSAT LMG/AR, which is currently the Mk200.

Atm., AAF/CSAT/FIA are identical in their ARs and MMGs. With CSAT changing to Zafir/Navid, AAF and FIA could keep the Mk200 as AR and use either of the new MMGs.

Reasoning is that the caliber of the new MMGs (.338 and 9.3x64mm) is a noticeable jump upwards, while the gap between Zafir (7.62x54mm) and Mk200 (6.5x3.9mm) is less so.

**Comment by Wolfenswan** [comment]
We're currently not using the AT/AP titan version in any of the factions. The "Hat" spot is occupied by the crew for the static HAT, medium AT is always a "RAT with more ammo". Which role should get the mobile Titan?
