### ISSUE TITLE
Ability to end safestart from admin briefing

### ISSUE THREAD

**Issue by Poulern** [ferstaberinde/F3#599]
I was writing a whole paragraph about what led me to this request, but i realized It's easier if i just requested it.

**Comment by Wolfenswan** [comment]
This what you had in mind?
https://i.imgur.com/km1a2So.jpg

**Comment by Poulern** [comment]
That's exactly what I had in mind. Having something like that would be
awesome.

**Comment by Wolfenswan** [comment]
Merged into dev.
