### ISSUE TITLE
Spectator: Disable or move "help" window on start

### ISSUE THREAD

**Issue by Wolfenswan** [ferstaberinde/F3#607]
Instead display a smaller "toggle H for help" hint, add a "help" menu option next to the display modes or move the window to a corner if not-displaying is not an option. Reason being that it can disrupt people's recording and is slightly intrusive.

**Comment by ferstaberinde** [comment]
Head - I am not going to assign this to 3-3-0 unless you feel it can be done in the next 48 hours.

**Comment by headswe** [comment]
Lets just take this one the next time, too much on the plate atm with swifty.

**Comment by ferstaberinde** [comment]
Cool - moving to future milestone for now.

**Comment by Wolfenswan** [comment]
This has happened with the latest version.
