### ISSUE TITLE
F3 3-2-3/3-3-0 Wiki updates

### ISSUE THREAD

**Issue by Wolfenswan** [ferstaberinde/F3#608]
- [x] F3 Admin Briefing (safe start menu)
- [x] F3 Safe Start (add Tip referring to admin menu)
- [x] F3 Assign Gear (add Marksman type)
- [x] F3 Set AI Skill Selector (update values) 
- [x] F3 Nametags component (update options, documentation & screenshots)
- [x] F3 Radio Support (ACRE2) @Sniperhid

**Comment by Sniperhid** [comment]
Updated the Dev F3 Radio Systems page for the ACRE2 implementation update (not really much to change)  - http://ferstaberinde.com/f3/en//index.php?title=Dev_Radio_Systems_Support

**Comment by ferstaberinde** [comment]
Assigning this to the 3-3-0 milestone.
