### ISSUE TITLE
[Radios] Removal of ACRE1 support

### ISSUE THREAD

**Issue by Sniperhid** [ferstaberinde/F3#614]
Keeping F3 well maintained is a key priority. Development for ACRE1 in Arma 3 stopped long ago. It seems all communities that use F3 are no longer using ACRE1 (correct us if we are wrong). ACRE2 will soon release their first non-beta version. When this occurs I propose that we drop ACRE1 support for F3 as it would appear to be dead weight.

If your community is still using ACRE1 feel free to get in touch and we can discuss this.

**Comment by headswe** [comment]
Agreed

**Comment by Wolfenswan** [comment]
Agreed and I suggest to cross-post this either with or shortly after the 3-3-0 release announcement.

**Comment by ferstaberinde** [comment]
@Sniperhid - is this something you still have time to do, or can we safely push this off to a post v3-4-0 release?

**Comment by ferstaberinde** [comment]
Merged in via #711
