### ISSUE TITLE
Broken paramsArray (Arma 3 1.44) - Aka no backpacks

### ISSUE THREAD

**Issue by Sniperhid** [ferstaberinde/F3#641]
paramsArray is no longer available during preInit on the server.

Ticket made here:
http://feedback.arma3.com/view.php?id=24007

**Comment by Pasrules** [comment]
To fix older missions still loaded onto our server I implemented a fix to the MCC mod's config.ccp
I believe this fix forced all backpack values to the default "1".

class Extended_PreInit_EventHandlers {
	class FA_preInit {
		serverinit = "f_param_backpacks = 1; publicVariable 'f_param_backpacks';"
	};
};
//MCC code below
#include "BIS_AddonInfo.hpp"
class CfgPatches

**Comment by cptnnick** [comment]
/u/Pasrules also points at a possible issue with the AGM parameter: http://www.reddit.com/r/arma/comments/375vl9/custom_f3_framework_build_for_mission_makers_rhs/crolzxy

This is most likely due to the medical parameter not being loaded correctly. 

@poulern, have you guys experienced issues with this?

**Comment by Sniperhid** [comment]
Nick this is true any parameters called during unit Init's are what is broken ACE/AGM gear for vehicles will be broken at that point. I can't recall if the ACE gear script replacement happens then or is it part of init.sqf (which is okay). In short anything that relies on assignGear and parameters will  be broken for now.

Pasrules is right about that fix that Wolenswan proposed, guess he forgot to post it here (Wolfenswan is one of of us too) - http://forums.bistudio.com/showthread.php?149231-F3-Mission-Development-Framework-(F2-for-ArmA-3)&p=2932229&viewfull=1#post2932229

According to our latest intel from BI all we know is that this is assigned so supposedly being worked on, but we don't know if this means it is in a queue or is confirmed as being a bug yet.

**Comment by Pasrules** [comment]
Thanks Sniper i was searching for where i found that piece of code so i could reference it.

**Comment by cptnnick** [comment]
ACE will be broken as well, it has a function running in preInit.

**Comment by Pasrules** [comment]
Just for reference there is no issue with the AGM parameter, using the entire array ["v_ifv",this,"side"] fixed the issue as RHS has its own "side"s

**Comment by mr-bo-jangles** [comment]
Has 1.46 offered a fix for this issue?

**Comment by cptnnick** [comment]
http://dev.arma3.com/post/spotrep-00043


   - Fixed: paramsArray available during the pre-init on the server

Seems to be so.

**Comment by captainblaffer** [comment]
Sorry, made a duplicate issue: https://github.com/ferstaberinde/F3/issues/654

1.46 didn't fix the problem for me...

**Comment by Sniperhid** [comment]
Confirmed fixed in 1.46
