### ISSUE TITLE
Move CfgFunctions F3 definitions into its own hpp file.

### ISSUE THREAD

**Issue by JonBons** [ferstaberinde/F3#643]
When I was working with someone in the framework they got confused with all the pre-defined definitions so in a fork of F3 we moved the functions into its own config.hpp containing the "class F" definitions and it helped clean up the file a bit and made merges for updating the framework on older missions easier because all I had to do was replace the "f" folder and update the config.hpp inside the folder.

Just a suggestion but it may confuse people updating their existing missions to the latest version.

**Comment by Wolfenswan** [comment]
I agree. Spectator and SWS already do this and it could easily be moved into a .hpp file in /common/ for the less function heavy components

**Comment by ferstaberinde** [comment]
Making this in-scope for v3-4-0 and assigning to @Wolfenswan

**Comment by Wolfenswan** [comment]
Closing as it has been merged.
