### ISSUE TITLE
Add Team Leaders to MMG, MAT etc.

### ISSUE THREAD

**Issue by Przemro** [ferstaberinde/F3#651]
Since TaskForceRadio add (backpack) radios that have less cargo space than backpack, I think it is good idea to add Team Leaders to teams like MMG. Then MMG gunner don`t lose his backpack for sake of radio. I gues it is easier than editing scripts to force TFR to not giving radios to MMG etc.

**Comment by cptnnick** [comment]
It's pretty easy to make TFR not hand out the backpacks. Would this be
preferred over an ORBAT change?

**Comment by Pasrules** [comment]
Just for some insight when we have any of the two man teams the lead drops his radio and recovers his backpack and then the group joins onto another squad using AGM ingame. We are more suited to two man weapons teams due to our size.

**Comment by cptnnick** [comment]
Are you sure you enabled the TFR param? There shouldnt be dropped bags on
the ground.

**Comment by Sniperhid** [comment]
The assistant gunner is already the team leader and should get the radios not the gunner?

For Vanilla/ACRE2 communities this is a non-issue, doesn't TFAR have 'long-range' radios that aren't backpacks?

**Comment by Pasrules** [comment]
False alarm this is just me being clumsy again.
