### ISSUE TITLE
description.ext parameters still broken in 1.46

### ISSUE THREAD

**Issue by captainblaffer** [ferstaberinde/F3#654]
When using F3 on a multiplayer dedicated server, most parameter variables are undefined for the player (not for server)

e.g. f_var_debugMode,f_param_backpacks etc.

some parameters are defined. like these: f_param_weather  f_param_fog f_param_timeOfDay

**Comment by captainblaffer** [comment]
The issues I've been having may be caused by these changes I've added in my mission:
https://github.com/ferstaberinde/F3/pull/623/files 

 			class processParamsArray
  			{
  				preInit = 1;
 -				postInit = 1;
  			};

Note the removed postInit line. I'll have to test more and let you guys know how it went.

**Comment by whiztler** [comment]
> PreInit set 1 to call the function upon mission start, **before objects are initialized**. Passed arguments are ["preInit"]

> PostInit set 1 to call the function upon mission start, **after objects are initialized.** Passed arguments are ["postInit"]

Perhaps init post rather than pre.

**Comment by cptnnick** [comment]
Params array pre processor needs to parse the mission parameters in preInit
for assignGear, which runs from the init field. So it needs to be ran at
least in preInit.

**Comment by captainblaffer** [comment]
I need to access the paramsarray post init as well for several reasons.

- Respawning players gear
- Spawning AI gear
- Headless client detection (I have a param that allows/disallows HC)

re-adding this line fixed the problem for me:
```postInit = 1;```

**Comment by Sniperhid** [comment]
There are indeed several minor problems with the current parameter processor I had just completed a rewrite pre-1.44, but I haven't pushed it yet. The trick is to run the parameter process on the server during preInit and publicVar the parameters, the public varing in the current F3 release is a bit dodgey. Also in single player loading default parameter values at preInit will make the single player editor viable again.

**Comment by Sniperhid** [comment]
see #657 for the proposed overhaul, been running this nicely in my fork!

**Comment by ferstaberinde** [comment]
@Sniperhid - unless you object, making this part of v3-4-0 and assigning to you ;)

**Comment by ferstaberinde** [comment]
Closing as this  #657 has been merged.
