### ISSUE TITLE
[Question] RHS Vehicles

### ISSUE THREAD

**Issue by Khaosmatic** [ferstaberinde/F3#655]
So, I've gotten back into F3 after a while and I've been trying to script some RHS stuff, more specifically the vehicles. I put down a bog standard .50cal Humvee and put ["v_car",this] call f_fnc_assignGear on the vehicle but whenever I load it, the vehicle spawns with its default RHS gear however when I swap it out for a vanilla Hunter the F3 gear goes straight in.

Any idea if this is on RHS' part with some script they use to gear their vehicles?

**Comment by cptnnick** [comment]
Even empty vehicles retain their original faction, which in this case wont
be the vanilla blu_f faction. Read the wiki article on assignGear,
specifically the section on how to force faction.

Basically treat vehicle cargo as you would an ammobox.

**Comment by Khaosmatic** [comment]
Aha! Thank you very much that is working great. I have never had to do that before hence the confusion but thank you very much nick. Hot diggity damn that was a quick response!
