### ISSUE TITLE
Safe base

### ISSUE THREAD

**Issue by Przemro** [ferstaberinde/F3#656]
Is there a way that you could add something like safe base. I mean here area where weapons are always off?

**Comment by cptnnick** [comment]
Trigger. Activation: `player in thisList`

On activation: `[true] call f_fnc_safety`

On deactivation: `[false] call f_fnc_safety`

Should work, but it's been a long day so let me know!

**Comment by Przemro** [comment]
@cptnnick what you wrote is not working as I need.

I have created new script in my version of F3, and it is working quite well, there is one big problem with ACE fragmentation.

#define SAFETY_ZONES    [["respawn_west", 300],["respawn_guerrila",300],["respawn_east",300]] // Syntax: [["marker1", radius1], ["marker2", radius2], ...]
#define MESSAGE "Strzelanie/rzucanie granatow zabronione!"

if (isDedicated) exitWith {};
waitUntil {!isNull player};

player addEventHandler ["Fired", {
    if ({(_this select 0) distance getMarkerPos (_x select 0) < _x select 1} count SAFETY_ZONES > 0) then
    {
    	player allowDamage false;
        deleteVehicle (_this select 6);
        titleText [MESSAGE, "PLAIN", 3];
    };
}];

**Comment by Przemro** [comment]
Also you need to call it from init.sqf

// ====================================================================================

//Addition of safezone
[] execVM "f\Safezone\Safezone.sqf";

// ====================================================================================

**Comment by Wolfenswan** [comment]
Can this be closed? This seems to be more of an ACE issue now.

**Comment by Przemro** [comment]
Well ACE removed fragmentation, and I managed to get this working correctly so it can be closed. Thanks for help.
