### ISSUE TITLE
Spectator chat question

### ISSUE THREAD

**Issue by Khaosmatic** [ferstaberinde/F3#658]
Is it intentional or a known error that in the spectator function you cannot hear those alive with TFAR? I noticed the other day it is still happening after a few updates and I have read the radios support some more but cannot find out if it is there or not?

**Comment by cptnnick** [comment]
This is not possible in TFR as far as I'm aware.

**Comment by Khaosmatic** [comment]
Oh right, damn I thought TFAR supported it. Thanks for the info nnick.

**Comment by Wolfenswan** [comment]
Closing as question has been answered.
