### ISSUE TITLE
game ctd in spectator script

### ISSUE THREAD

**Issue by Boberro** [ferstaberinde/F3#661]
So I was spectating AI helicopter from first person view, when Zeus deleted that unit. Game crashed violently with some kind of "-12339578234953" out of memory error.

**Comment by cptnnick** [comment]
Could you try uploading your .rpt file to pastebin and link it here?

**Comment by Boberro** [comment]
http://pastebin.com/raw.php?i=qszueZ5t

**Comment by cptnnick** [comment]
This is the information currently available on that exit code:

https://community.bistudio.com/wiki/Arma_3_Unusual_process_exit#0xC0000005_-_ACCESS_VIOLATION

Try following those instructions.

It's not an error explicitly caused by one of the scripts.

**Comment by Wolfenswan** [comment]
Closing this as it's not caused by F3.
