### ISSUE TITLE
[Question] Gear selector screen

### ISSUE THREAD

**Issue by Khaosmatic** [ferstaberinde/F3#662]
Hey guys so with the release of the new 3CB Gear Pack some thing has long been on my mind being the selector of certain gear on an in-game menu? For example there are like 20 types of helmet, or RHS has 10 types of M4 with different grips, etc. It would be awesome if there was an overlay that could be initialized after you load in like shown at the start of this video:

https://www.youtube.com/watch?v=G672jxCAERM

Or is it possible to do something similar where you could lock a virtual arsenal crate to different set classes in F3 like 'gren' or 'co'

**Comment by Khaosmatic** [comment]
If not, is it possible to do a random array of gear for a certain class like how you can randomize the default clothing? E.g only grenadiers get the grenadier backpack randomization, etc.

**Comment by Pasrules** [comment]
I'd love Bohemia to implement a filter function for the arsenal, we have that same problem you mentioned with the variety.
For my group i just made some extra classes for supply crates that compliment the loadouts that way we don't need an arsenal. However a specific arsenal is what we use should we need one, which stops everybody grabbing sniper scopes etc...

**Comment by Sniperhid** [comment]
@Pasrules You already can limit the aresnal. Here is a script I wrote sometime back - http://pastebin.com/S22yjAJc 
https://community.bistudio.com/wiki/Arsenal - Has all the functions.

Personally I just use the randomization in F3's assign Gear or create more randomization in the gear script (yes it is possible). I am not a fan of letting players suffer from shiny gear syndrome (aka where they spend lots of time picking gear etc.) as it slows rollout times, obviously this is a community by community decision.

**Comment by Khaosmatic** [comment]
Yep, that is the exact situation I hate too. So how would I go about setting randomized gear for a set class as doesn't F3 just choose a vest based on the parameter for equipment size? For the backpacks I've got a rough idea, where it is defined can I just do:

_baggrenadier = ["classname1","classname2","classname3"]; ?

**Comment by Sniperhid** [comment]
_baggrenadier = ["classname1","classname2","classname3"] call BIS_fnc_selectRandom; // This should do it

**Comment by Khaosmatic** [comment]
I see, I will definitely give it a try and report back.

**Comment by Pasrules** [comment]
That's a good bit of code sniper, i know of limiting the arsenal. I was looking more into a search or filter function so you can separate the guns of robert hammer and red hammer, but i think this is more a mod than a framework possibility. Framework wise is it possible to limit the arsenal to each class so the shiny gear syndrome doesn't occur. This may seem like alot of code for each class tho unless a global and specific piece are written.

**Comment by Sniperhid** [comment]
Yeah you would have to do it by class, but you could retrive the assignGear variable that is placed on the player's unit to find their class out, and adjust it appriotrately but it is a lot of code. Personally I think this is a bit outside of the scope of Vanilla F3. 


There are issues with the aresnal and gear synchorization, iirc adding and removing the same uniform on the same frame causes issues. (ACRE2 will bug out as a a result of the gear being de-synchronized and won't let you forget it).

**Comment by Khaosmatic** [comment]
Do any of you find gentlemen know how I would set vests per class? Would it be done by creating a new "class" like Ghillie or Diver?

**Comment by cptnnick** [comment]
I normally switch out custom vests or helmets for specific classes just after the uniform is assigned, but before any items are added. Simply adding a new class won't work, as the clothing function won't recognize them.
