### ISSUE TITLE
[Question] How to combine sqf files so both work.

### ISSUE THREAD

**Issue by Khaosmatic** [ferstaberinde/F3#663]
Hi so I found out the Insurgency Alive mission is completely open source so anyone can take it and add to it. So I noticed it has its own description.ext and init.sqf and I would like to use F3 alongside it except I don't exactly know how I would combine the two files? I will put the Insurgency and F3 description.ext to show it more clearly.

**Comment by Khaosmatic** [comment]
/*
  _____
  \_   \_ __  ___ _   _ _ __ __ _  ___ _ __   ___ _   _
   / /\/ '_ \/ __| | | | '__/ _` |/ _ \ '_ \ / __| | | |
/\/ /_ | | | \__ \ |_| | | | (_| |  __/ | | | (__| |_| |
\____/ |_| |_|___/\__,_|_|  \__, |\___|_| |_|\___|\__, |
                            |___/                 |___/

@filename: description.ext

Author:

	Hazey

Last modified:

	2/20/2015

Description:

	Contains the main defines and params.
______________________________________________________*/

//--- System Header
class header {
	gametype = COOP;
	minplayers = 1;
	maxplayers = 24;
	playerCountMultipleOf = 1;  //Coop type missions use 1, Team type missions use 2
};

//--- Mission Title
author = "Alive Dev Team | Mission by Hazey";
onLoadMission = "Welcome to Insurgency | ALiVE. Find and destroy the hidden weapons caches. Use your map to find possible cache locations.";
onLoadIntroTime = true;
onLoadMissionTime = true;
onLoadName = Insurgency | ALiVE;
loadScreen = "media\logo_INS.paa";

//--- General Settings
aiKills = 0;
briefing = 1;
debriefing = 1;
allowFunctionsRecompile = 1;

//--- Debug
enableDebugConsole = 1;

//--- Respawn
respawn = BASE;
respawnDelay = 15;
respawnDialog = 1;
disabledAI = 1;
respawnTemplates[] = {"MenuPosition"};
respawnButton = 0;
respawnOnStart = 0;

//--- General Includes

//--- Intro Sounds/ Others
class CfgSounds {
	sounds[] = {news,prayer};

	class news {
		name = "news";
		sound[] = {"media\sounds\news.ogg", db+0, 1.0};
		titles[] = {};
	};

	class prayer {
		name = "prayer";
		sound[] = {"media\sounds\prayer.ogg", db+1, 1};
		titles[] = {};
	};
};

//--- Custom Intel Event Handlers
class Extended_InitPost_EventHandlers {
    class Man {
        //--- Make sure everyone is happy when the mission starts
		init = "_this call INS_fnc_handlerRegister";
    };
};

//--- CfgFunctions
class CfgFunctions{
	#include "functions\cfgfunctions.hpp"
};

//--- Params
class Params {

	class EmtpyLine1 {
		//--- paramsArray[0]
		title = ":: General Settings";
		values[]={0,0};
		texts[]={ "",""};
		default = 0;
	};

	class INS_STARTTIME {
		title = "Mission Start Time";
		values[] = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24};
		texts[] = {
			"1:00","2:00","3:00","4:00","5:00","6:00","7:00","8:00","9:00","10:00","11:00","12:00",
			"13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00","22:00","23:00","24:00"
		};
		default = 6;
		function = "BIS_fnc_paramDaytime";
	};

	class INS_CallToPrayer {
		//--- paramsArray[2]
		title = "Civilian Call To Prayer";
		values[] = {1,0};
		texts[] = {"Enabled","Disabled"};
		default = 1;
	};

	class EMPTYPARAM {
		//--- paramsArray[3]
		title = "Empty Param";
		values[] = {0};
		texts[] = {"Disabled"};
		default = 0;
	};

	class INS_ADVANCEDROLES{
		//--- paramsArray[4]
		title = "Advanced Roles: Specialty Utilities.";
		values[] = {1,0};
		texts[] = {"Enabled","Disabled"};
		default = 1;
	};

	class EmtpyLine2 {
		//--- paramsArray[5]
		title = ":: Core Settings";
		values[]={0,0};
		texts[]={ "",""};
		default = 0;
	};

    class cachesLimit {
		//--- paramsArray[6]
		title = "Number of caches to hunt";
		values[] = {2,4,6,8,10,12,14,16};
		texts[] = {"Two","Four","Six","Eight","Ten","Twelve","Fourteen","Sixteen"};
		default = 6;
	};

	class intelItems {
		//--- paramsArray[7]
		title = "Spawn Intel in town?";
		values[] = {1,0};
		texts[] = {"Enabled","Disabled"};
		default = 0;
	};

	class intelAmount {
		//--- paramsArray[8]
		title = "Number of Intel Items to spawn per town";
		values[] = {2,4,6,8,10};
		texts[] = {"2","4","6","8","10"};
		default = 4;
	};

	class EMPTYPARAM1 {
		//--- paramsArray[9]
		title = "Empty Param";
		values[] = {0};
		texts[] = {"Disabled"};
		default = 0;
	};

	class INS_dropRate {
		//--- paramsArray[10]
		title = "Intel drop rate - off bodies";
		values[] = {98,95,92,87,84,80,77,75,70};
		texts[] = {"2% Chance","5% Chance","8% Chance","13% Chance","16% Chance","20% Chance","23% Chance","25% Chance","30% Chance"};
		default = 95;
	};

	class INS_MHQ {
		//--- paramsArray[11]
		title = "Insurgency MHQ - WIP";
		values[] = {1,0};
		texts[] = {"Enabled","Disabled"};
		default = 1;
	};

	class INS_MHQ_DeployTime {
		//--- paramsArray[12]
		title = "MHQ Deploy Time.";
		values[] = {10,20,30,60,120,300};
		texts[] = {"10 Seconds","20 Seconds","30 Seconds","60 Seconds","2 Minutes","5 Minutes"};
		default = 30;
	};

};

**Comment by Khaosmatic** [comment]
// ============================================================================================

// F3 - Mission Header
// Credits: Please see the F3 online manual (http://www.ferstaberinde.com/f3/en/)

class Header
{
	gameType = Coop;
	minPlayers = 1;
	maxPlayers = 28;
};

// ============================================================================================

// F3 - Loading Screen
// Credits: Please see the F3 online manual (http://www.ferstaberinde.com/f3/en/)

onLoadName = "Fueled Up Fever";
onLoadMission = "Search & Destroy";
author = "Made by Khaos";
loadScreen = "mylogo.paa";

// ============================================================================================

// F3 - Debug Console
// Credits: Please see the F3 online manual (http://www.ferstaberinde.com/f3/en/)

enableDebugConsole = 1;

// ============================================================================================

// F3 - Respawn Settings
// Credits: Please see the F3 online manual (http://www.ferstaberinde.com/f3/en/)

respawn = 1;
respawndelay = 3;
respawnOnStart = 0;
respawnTemplates[] = {"f_spectator"};

// ============================================================================================


// F3 - Start of Notifications block.

class cfgNotifications
{
	// Notification Template
	class Template
	{
		title = ""; // Tile displayed as text on black background. Filled by arguments.
		iconPicture = ""; // Small icon displayed in left part. Colored by "color", filled by arguments.
		iconText = ""; // Short text displayed over the icon. Colored by "color", filled by arguments.
		description = ""; // Brief description displayed as structured text. Colored by "color", filled by arguments.
		color[] = {1,1,1,1}; // Icon and text color
		duration = 5; // How many seconds will the notification be displayed
		priority = 0; // Priority; higher number = more important; tasks in queue are selected by priority
		difficulty[] = {}; // Required difficulty settings. All listed difficulties has to be enabled
	};

	// A generic warning notification
	class Alert
	{
		title = "ALERT";
		description = "%1";
		iconPicture="\A3\ui_f\data\map\markers\military\warning_ca.paa";
		duration = 3;
		priority = 9;
	};

	// Notifications for the F3 Safe Start Component
	class SafeStart
	{
		title = "SAFE START";
		description = "%1";
		iconPicture="\A3\UI_F\data\IGUI\Cfg\Actions\settimer_ca.paa";
		duration = 10;
		priority = 0;
	};
	class SafeStartMissionStarting
	{
		title = "SAFE START";
		description = "%1";
		iconPicture="\A3\UI_F\data\IGUI\Cfg\Actions\settimer_ca.paa";
		duration = 3;
		priority = 1;
	};

	// Notification for the F3 Authorised Crew Component
	class UnauthorisedCrew {
		title= "NON-AUTHORISED CREW!";
		description= "%1";
		iconPicture = "\A3\ui_f\data\map\markers\military\warning_ca.paa";
		duration = 3;
		priority = 5;
	};

	// Notification for the F3 Mapclick Teleport component
	class MapClickTeleport {
		title= "NOTE";
		description= "%1";
		iconPicture = "\A3\ui_f\data\map\markers\military\start_ca.paa";
		duration = 3;
		priority = 5;
	};

	// Notification for the F3 JIP Component
	class JIP {
		title= "REINFORCEMENTS";
		description= "%1";
		iconPicture = "\A3\ui_f\data\map\markers\military\flag_ca.paa";
		duration = 3;
		priority = 5;
	};
};

// ============================================================================================

// F3 - Start of Params code blocks.
// WARNING: DO NOT DELETE OR COMMENT OUT THIS CODE BLOCK

class Params
{

// ============================================================================================

// F3 - Debug Mode
// Credits: Please see the F3 online manual (http://www.ferstaberinde.com/f3/en/)
// WARNING: DO NOT DISABLE THIS COMPONENT

    class f_param_debugMode
    {
            title = "$STR_f_param_debugMode";
            values[] = {0,1};
            texts[] = {"Off","On"};
            default = 0;
            code = "f_var_debugMode = %1";
    };

// ============================================================================================

// F3 - Folk Assign Gear Script
// Credits: Please see the F3 online manual (http://www.ferstaberinde.com/f3/en/)

    class f_param_backpacks
    {
            title = "$STR_f_param_loadouts";
            values[] = {0,1,2};
            texts[] = {"Light","Medium","Heavy"};
            default = 1;
            code = "f_param_backpacks = %1";
    };

// ============================================================================================

// F3 - Radio Systems Support
// Credits: Please see the F3 online manual (http://www.ferstaberinde.com/f3/en/)

    class f_param_radios
    {
            title = "Radio System";
            values[] = {0,1,2,3};
            texts[] = {"Off","ACRE","TFR","ACRE2"};
            default = 2;
            code = "f_var_radios = %1";
    };

// ============================================================================================

// F3 - Medical Systems Support
// Credits: Please see the F3 online manual (http://www.ferstaberinde.com/f3/en/)

    class f_param_medical
    {
            title = "Medical System";
            values[] = {0,1,2};
            texts[] = {"Arma 3 Default","F3 Simple Wounding System","Authentic Gameplay Mod"};
            default = 2;
            code = "f_var_medical = %1";
    };

// ============================================================================================

// F3 - Mission Timer/Safe Start
// Credits: Please see the F2 online manual (http://www.ferstaberinde.com/f3/en/)

    class f_param_mission_timer
    {
            title = "$STR_f_param_mission_timer";
            values[] = {0,1,2,3,4,5,6,7,8,9,10,15};
            texts[] = {"$STR_f_param_mission_timer_off","1","2","3","4","5","6","7","8","9","10","15"};
            default = 5;
            code = "f_param_mission_timer = %1";
    };

// ============================================================================================

// F3 - Mission Conditions Selector
// Credits: Please see the F3 online manual (http://www.ferstaberinde.com/f3/en/)

	class f_param_weather
	{
		title = "$STR_f_param_weather";
		values[] = {0,1,2,3,4,5,6,7,8};
		texts[] = {$STR_f_param_weather_Option0,$STR_f_param_weather_Option1,$STR_f_param_weather_Option2,$STR_f_param_weather_Option3,$STR_f_param_weather_Option4,$STR_f_param_weather_Option5,$STR_f_param_weather_Option6,$STR_f_param_weather_Option7,$STR_f_param_weather_Option8};
		default = 1;
		function = "f_fnc_setWeather";		// This function is called to apply the values
		isGlobal = 0;						// Execute this only on the server
		code = "f_param_weather = %1";
	};

	class f_param_fog
	{
		title = "Fog";
		values[] = {0,1,2};
		texts[] = {"None","Light","Heavy"};
		default = 0;
		function = "f_fnc_SetFog";			// This function is called to apply the values
		isGlobal = 0;						// Execute this only on the server
		code = "f_param_fog = %1";
	};

    class f_param_timeOfDay
	{
		title = "$STR_f_param_timeOfDay";
		values[] = {0,1,2,3,4,5,6,7};
		texts[] = {$STR_f_param_timeOfDay_Option0,$STR_f_param_timeOfDay_Option1,$STR_f_param_timeOfDay_Option2,$STR_f_param_timeOfDay_Option3,$STR_f_param_timeOfDay_Option4,$STR_f_param_timeOfDay_Option5,$STR_f_param_timeOfDay_Option6,$STR_f_param_timeOfDay_Option7};
		default = 4;
		function = "f_fnc_setTime";			// This function is called to apply the values
 		isGlobal = 0;						// Execute this only on the server
 		code = "f_param_timeOfDay = %1";
	};

// ============================================================================================

// F3 - AI Skill Selector
// Credits: Please see the F3 online manual (http://www.ferstaberinde.com/f3/en/)
//
//	class f_param_AISkill_BLUFOR
//	{
//		title = "$STR_f_param_AISkill_BLUFOR";
//		values[] = {0,1,2,3};
//		texts[] = {$STR_f_param_AISkill_Option0,$STR_f_param_AISkill_Option1,$STR_f_param_AISkill_Option2,$STR_f_param_AISkill_Option3};
//		default = 1;
//		code = "f_param_AISkill_BLUFOR = %1";
//	};
//
//	class f_param_AISkill_OPFOR
//	{
//		title = "$STR_f_param_AISkill_OPFOR";
//		values[] = {0,1,2,3};
//		texts[] = {$STR_f_param_AISkill_Option0,$STR_f_param_AISkill_Option1,$STR_f_param_AISkill_Option2,$STR_f_param_AISkill_Option3};
//		default = 3;
//		code = "f_param_AISkill_OPFOR = %1";
//	};
//
	class f_param_AISkill_INDP
	{
		title = "$STR_f_param_AISkill_INDP";
		values[] = {0,1,2,3};
		texts[] = {$STR_f_param_AISkill_Option0,$STR_f_param_AISkill_Option1,$STR_f_param_AISkill_Option2,$STR_f_param_AISkill_Option3};
		default = 2;
		code = "f_param_AISkill_INDP = %1";
	};

// ============================================================================================

// F3 - Caching
// Credits: Please see the F3 online manual (http://www.ferstaberinde.com/f3/en/)

	class f_param_caching
	{
		title = "Cache AI outside distance (m)";
		values[] = {0,600,800,1000,1500,2000};
		default = 0;
		code = "f_param_caching = %1";
	};

// ============================================================================================

// F3 - End of Params code blocks.
// WARNING: DO NOT DELETE OR COMMENT OUT THIS CODE BLOCK

};

// ============================================================================================

// F3 - Briefing Template
// Credits: BIS - Please see the F3 online manual (http://www.ferstaberinde.com/f3/en/)

class CfgDebriefing
{
	class End1
	{
		title = "Mission Failed";
		subtitle = "";
		description = "Your entire scrub force was eliminated";
		// pictureBackground = "";
		// picture = "";
		// pictureColor[] = {0.0,0.3,0.6,1};
	};

	class End2
	{
		title = "Mission Complete";
		subtitle = "";
		description = "The village was cleared of those pesky CSAT Forces!";
		// pictureBackground = "";
		// picture = "";
		// pictureColor[] = {0.0,0.3,0.6,1};
	};

	class End3
	{
		title = "Ending #3";
		subtitle = "";
		description = "*** Insert debriefing #3 here. ***";
		// pictureBackground = "";
		// picture = "";
		// pictureColor[] = {0.0,0.3,0.6,1};
	};

	class End4
	{
		title = "Ending #4";
		subtitle = "";
		description = "*** Insert debriefing #4 here. ***";
		// pictureBackground = "";
		// picture = "";
		// pictureColor[] = {0.0,0.3,0.6,1};
	};

	class End5
	{
		title = "Ending #5";
		subtitle = "";
		description = "*** Insert debriefing #5 here. ***";
		// pictureBackground = "";
		// picture = "";
		// pictureColor[] = {0.0,0.3,0.6,1};
	};

	class End6
	{
		title = "Ending #6";
		subtitle = "";
		description = "*** Insert debriefing #6 here. ***";
		// pictureBackground = "";
		// picture = "";
		// pictureColor[] = {0.0,0.3,0.6,1};
	};

};

// ============================================================================================

// F3 - Respawn Templates
// Credits: Please see the F3 online manual (http://www.ferstaberinde.com/f3/en/)

class CfgRespawnTemplates
{
	// F3 Spectator Script
	class f_Spectator
	{
		onPlayerRespawn = "f_fnc_CamInit";
	};

	// F3 JIP Menu
	class f_JIP
	{
		onPlayerRespawn = "f\JIP\f_JIP_playerRespawn.sqf";
	};
};

// ============================================================================================

// F3 - Menu components
// DO NOT REMOVE OR DISABLE THIS BLOCK OF CODE

// Menu components for the JIP Menu
#include "f\JIP\f_JIP_kitpicker.h"
#include "f\JIP\f_JIP_grppicker.h"

// Menu components for the Spectator Script
#include "f\spect\config.hpp"

// ============================================================================================

// F3 - Functions
// DO NOT REMOVE OR DISABLE THIS BLOCK OF CODE

class CfgFunctions
{
	class F // Defines the "owner"
	{
		class common // category
		{
			file = "f\common";
			// Defines the function to preInit (the paramArray dosent seem to be constructed at preInit stage).
			class processParamsArray
			{
				preInit = 1;
				postInit = 1;
			};

			class nearPlayer{};
		};
		class mpEnd
		{
			file = "f\mpEnd";
			class mpEnd{};
			class mpEndReceiver{};
		};
		class assignGear
		{
			// Defines the functions to preInit the compling of the assignGear function used by units.
			file = "f\assignGear";
			class assignGear{};
		};
		class setGroupID
		{
			file = "f\setGroupID";
			class setGroupID{};
		};
		class missionConditions
		{
			file = "f\missionConditions";
			class SetTime{};
			class SetFog{};
			class SetWeather{};
		};
		class cache
		{
			file = "f\cache";
			class cInit {};
			class cTracker {};
			class gCache {};
			class gUncache {};
		};
		class groupMarkers {
			file = "f\groupMarkers";
			class localGroupMarker{};
			class localSpecialistMarker{};
		};
		class authorisedCrew
		{
			file = "f\authorisedCrew";
			class authorisedCrewCheck {};
		};
		class FTMemberMarkers
		{
			file = "f\FTMemberMarkers";
			class SetLocalFTMemberMarkers{};
			class GetMarkerColor{};
			class LocalFTMarkerSync{};
		};
		class bodyRemoval
		{
			file = "f\removeBody";
			class removeBody{};
		};
		class setAISkill
		{
			file = "f\setAISKill";
			class setAISKill{};
		};
		class mapClickTeleport
		{
			file = "f\mapClickTeleport";
			class mapClickTeleportUnit{};
			class mapClickTeleportGroup{};
		};
		class nametag
		{
			file = "f\nametag";
			class drawNameTag{};
		};
		class preMount
		{
			file = "f\preMount";
			class mountGroups{};
		};
		class zeus
		{
			file = "f\zeus";
			class zeusInit{};
			class zeusAddAddons{};
			class zeusAddObjects{};
		};
		class acre
		{
			file = "f\radios\acre";
			class acre_removeRadios{};
			class acre_addRadios{};
			class acre_setRadioFrequencies{};
			class acre_configureSpectatorChat{};
		};
		class tfr
		{
			file = "f\radios\tfr";
			class tfr_removeRadios{};
			class tfr_addRadios{};
			class tfr_setRadioFrequencies{};
			class tfr_configureSpectatorChat{};
		};
		#include "f\simplewoundingsystem\config.hpp"
		#include "f\spect\functions.hpp"

	};
};


// ============================================================================================

// F3 - Custom Insignia

class CfgUnitInsignia {
	#include "f\assignGear\insignia\define.hpp"
};

**Comment by Khaosmatic** [comment]
In hindsight that was probably really stupid to post those massive lines when all I need to know is how to combine them into one file....

**Comment by cptnnick** [comment]
The description.ext file is fundamentally differently structured from .sqf files.
They are structured the same way like arma's config files, but only a select few can be influenced from the .ext. Here is the article on them: https://community.bistudio.com/wiki/Description.ext.

You'll need to stitch them together nicely, making sure there aren't any double entries or conflicts. Doing so would be beyond the scope of the F3 team but if you have specific questions I would be glad to answer them for you.

**Comment by Khaosmatic** [comment]
I see, so it probably wouldn't work well if after the final }; on the F3 Description I added a space between it and the first lines of the Insurgency Description?
