### ISSUE TITLE
AAF JTAC CAS Support

### ISSUE THREAD

**Issue by Boberro** [ferstaberinde/F3#665]
In current version of F3, each side has JTAC synced with mortar and CAS helicopter. Apparently (see: http://feedback.arma3.com/print_bug_page.php?bug_id=20079) CAS module does not work with hellcat.
I'd suggest either removing hellcat CAS, to avoid confusion, or to change it to bombing run module.

**Comment by ferstaberinde** [comment]
Thanks for the heads-up, @Boberro - will add this to the open bugs list for v3-4-0

**Comment by Wolfenswan** [comment]
I tested this and can confirm it's still not working.
