### ISSUE TITLE
[Question] Adding scopes to launchers or pistols

### ISSUE THREAD

**Issue by Khaosmatic** [ferstaberinde/F3#666]
Hey guys, so with packs like TF47 Launchers or RH Pistol packs they have the ability to have attachments. I understand the normal attachments for rifles but how would I go about adding attachments such as a MAAW's scope which classname is 'tf47_m3maaws_optic'.

Any ideas?

**Comment by Khaosmatic** [comment]
I've just looked in the f_assignGear_attachments and have seen pistols, so I'd assume I'd have to add a new section for launchers?

**Comment by headswe** [comment]
Yes

**Comment by Pasrules** [comment]
For TF47 seeing as there is only one scope just put it straight into the class that is using it (down the bottom). RH Pistols have quite a few attachments so adding a couple extra _pbarrel, _pscope etc would work well.

**Comment by Wolfenswan** [comment]
Closing this as question has been answered.
