### ISSUE TITLE
[Question] Spectator Zeus

### ISSUE THREAD

**Issue by Khaosmatic** [ferstaberinde/F3#667]
Hey gents just a quick question, I went into spectator and looked to amp things up by doing some Zeus and noticed because I didn't before turn on all the stuff in Briefing > Administrator meant I had no resources/couldnt edit already placed units. Is there a way to activate those in spectator?

**Comment by Khaosmatic** [comment]
Bump

**Comment by cptnnick** [comment]
spawn and control a unit and then execVM briefing.sqf in the admin console?

**Comment by Khaosmatic** [comment]
I shall give that a whack when I can.

**Comment by Khaosmatic** [comment]
Apologies I forgot to close it, however a question where is the admin console? Just the normal Debug Console in the Esc Menu? If that is the case if that is executed server wide (I tried local and it didn't work) does that mean every player has the briefing open on their screen?
