### ISSUE TITLE
TFR Support

### ISSUE THREAD

**Issue by Pasrules** [ferstaberinde/F3#671]
A revision of f\radios\tfr\fn_tfr_addRadios is required as some of the classes do not match assignGear.
Also the two man weapons teams loose their deployable backpack in place for a long range radio.
Here is B|Tac's internal fix for both these problems https://github.com/Pasrules/F3_BTAC/tree/master/author_mission_px.Altis/f/radios/tfr

**Comment by ferstaberinde** [comment]
Adding this to the scope of v3-4-0. @Pasrules - would you be up for helping ensure this is implemented correctly?

**Comment by Pasrules** [comment]
I can submit a pull to update the radios to correct the class name bugs, and would like to get some opinions (discord) on what we should do with radios for weapons teams.

@ferstaberinde  I will take this task

**Comment by ferstaberinde** [comment]
Thanks @Pasrules - added you as a contributor and assigned you the task :)
