### ISSUE TITLE
[Question] Remove TFR Radio Programer

### ISSUE THREAD

**Issue by Pasrules** [ferstaberinde/F3#672]
How would i go about removing the TFR Radio programmer as i would like rifleman radios not to be edited from the pre set radio channels

**Comment by Khaosmatic** [comment]
Did you find out how? I'd be interested in knowing.

**Comment by cptnnick** [comment]
Set the global API variable TF_give_microdagr_to_soldier to false.

See:
https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API%3A-Variables
