### ISSUE TITLE
weather component

### ISSUE THREAD

**Issue by captainblaffer** [ferstaberinde/F3#673]
Suggestion to replace F3 setovercast and setfog commands with BIS_fnc_setFog and BIS_fnc_setOvercast, as it works better in MP and with mods (ACE).

relevant:
https://github.com/ferstaberinde/F3/tree/master/f/missionConditions
https://github.com/acemod/ACE3/issues/1552#issuecomment-134691437

**Comment by ferstaberinde** [comment]
Thanks for flagging this @captainblaffer - will add as component improvement for now, and we'll investigate.

**Comment by Wolfenswan** [comment]
Iirc the weather component does happen in non-scheduled environment, which rules out BIS_fnc_setOvercast.

BIS_fnc_setFog seems to do pretty much the same thing as F_fnc_setFog but I'll check if there are any major differences.

**Comment by captainblaffer** [comment]
The F3 framework uses Setfog and Setovercast commands, which do not work at all when in MP and using  ACE. Possibly won't work without using ACE too. What seems to happen is the server will overwrite whatever setting set on the client automatically.

I've already made these changes in my local version of the framework:
+[_strength,_decay,_base] call BIS_fnc_setFog;
-_transition setFog [_strength,_decay,_base];

+[_MissionOvercast] call BIS_fnc_setOvercast;
-if (typeName _transition == typeName 0) then {
-_transition setOvercast  _MissionOvercast;
-_transition setRain _MissionRain;
-_transition setRainbow _MissionRainbow;
-_transition setWindStr  _MissionWindStr;
-_transition setWindForce _MissionWindGusts;
-_transition setWaves _MissionWaves;
-_transition setLightnings _MissionLightnings;
-} else {
-	0 setOvercast  _MissionOvercast;
-	0 setRain _MissionRain;
-	0 setRainbow _MissionRainbow;
-	0 setWindStr  _MissionWindStr;
-	0 setWindForce _MissionWindGusts;
-	0 setWaves _MissionWaves;
-	0 setLightnings _MissionLightnings;
-	forceWeatherChange;
-};

**Comment by Wolfenswan** [comment]
thanks. The commands def. work in MP without ACE.

**Comment by Wolfenswan** [comment]
According to the ACE tracker this is mostly a BI issue. Closing this here as people can always opt to use BI functions or the in-editor settings if so desired.
