### ISSUE TITLE
New kind of objectives

### ISSUE THREAD

**Issue by Davanseth** [ferstaberinde/F3#675]
Hello there. (sorry my english)
Since all missions are not TDM, Is it possible to introduce new kind of objectives, and each one give an amount of points to the side who completed it (adversarial), and have a mission ending with the side who got more points wins, like:
-capture a zone (xxx points)
-trigger an action action on an item or someone (e.g. on a laptop or whatever) (xxx points)
-destroy/kill (an objet/item/building/bridge...) (xxx points)
-and so on with different kind of objectives...

And, with that, set a time limit on the mission, and a scoreboard with the total points earned and winner/looser?

Yeah, I know its a lot, sorry, but F3 is so good, we just want it to get better!

Thank you guys for your hard work, keep up the good work ;)

**Comment by ferstaberinde** [comment]
HI @Davanseth - Thanks for posting. I'm afraid that what you describe is more of a mission template. You could certainly build one with a framework like F3, but we would consider that kind of functionality out of scope for our project. There are some interesting A&D mission templates out there - have you explored the Steam Workshop and/or posted to /r/arma ? Hope you find what you are looking for :)
