### ISSUE TITLE
SWS: Downed players can occasionally move, fire

### ISSUE THREAD

**Issue by darkChozo** [ferstaberinde/F3#676]
Didn't see an existing issue for this, so...

Occasionally players downed with SWS enabled will still be able to move and fire. It looks like everything works aside from the downed animation; they see the red bleedout screen, they cannot use actions or reload, they can be revived (at which point the revive roll animation plays), and if they're not revived they eventually bleed out. However, they can move normally and can fire using the magazine already loaded in their weapon.

I personally haven't seen any obvious way of reproducing this but it pops up every so often in FA sessions.

**Comment by Wolfenswan** [comment]
Was fixed with #686
