### ISSUE TITLE
Feature request: Random objective generator

### ISSUE THREAD

**Issue by deleyt** [ferstaberinde/F3#677]
F3 is so extensive with all it's wonderful SQF modules where you can just take whatever you need and leave the rest out to keep a clean and tidy mission. Excellent!

I've always been a huge fan of missions that place random generated objectives simply because of replayability. Examples: TIER1's Combat Patrol Generator or EightySix's Patrol Ops.

Would the developing team consider adding something similar for F3?
A script where objectives can be placed within SQF files and a script pulling an objective from the pool?

**Comment by headswe** [comment]
Out of scope really.

**Comment by Pasrules** [comment]
This is a framework for building missions. I suggest you look at MCC4's campaign module for what you are looking for. F3 and MCC4 run together without any issues.

**Comment by ferstaberinde** [comment]
Hi @deleyt - I'm afraid this is something that we would consider out of scope. As @Pasrules writes, you may want to check out MCC4.
