### ISSUE TITLE
Sending end mission script to spectators

### ISSUE THREAD

**Issue by alexcroox** [ferstaberinde/F3#678]
I have a TvT gamemode and I have win/lose conditions depending on who is dead. The endmission fires OK for those who are alive but not for those who are in the spec cam. Is this because they no longer have a side? How do I target these players? This is my current script:

```
if (isServer) then {
	
	gameStart = false;

	_endGameThread = [] spawn {
	    while {true} do {

	    	waitUntil {
	    		_totalAlive = {alive _x} count allUnits;

	    		_totalAlive > 1 || gameStart;
	    	};

	    	gameStart = true;

	        _bluUnits = [];
	        _redUnits = [];
	        {
	            if (side _x == west ) then {
	                 _bluUnits pushBack _x;
	            };

	            if (side _x == east ) then {
	                 _redUnits pushBack _x;
	            };

	        } forEach allUnits;
	        
	        if (count _bluUnits == 0 ) exitWith {

	        	[["win",true,true],"BIS_fnc_endMission", east, false] call BIS_fnc_MP;
	        	[["fail",true,true],"BIS_fnc_endMission", west, false] call BIS_fnc_MP;
	        };
	        if (count _redUnits == 0 ) exitWith {

			    [["fail",true,true],"BIS_fnc_endMission", east, false] call BIS_fnc_MP;
	        	[["win",true,true],"BIS_fnc_endMission", west, false] call BIS_fnc_MP;
	        };

	        uiSleep 5;
	    };
	};
};

**Comment by Sniperhid** [comment]
Yes, spectators have the side 'logic' not sure the exact variable to use but it might be sideLogic -> https://community.bistudio.com/wiki/sideLogic

**Comment by headswe** [comment]
It is indeed sideLogic.

2015-09-26 14:54 GMT+02:00 Snippers <notifications@github.com>:

**Comment by alexcroox** [comment]
So there's no way to retrieve their previous side so I can send them a mission fail/win? Reason I ask here is I see the framework stores their previous unit before making them virtual.

**Comment by Wolfenswan** [comment]
A workaround could be to use set/getVariable with a player EH.

**Comment by headswe** [comment]
You need to set on spawn/init since once a unit is dead its instantly switched to civilian side.
