### ISSUE TITLE
[Feature Request] Day Night Cycle Acceleration

### ISSUE THREAD

**Issue by Pasrules** [ferstaberinde/F3#680]
Would it be possible to look into a parameter which multiplies the rate at which in game time passes?
MCC4 has a module for this but a framework parameter would be preferred to reduce mod dependability.

**Comment by Wolfenswan** [comment]
Easily, it only the requires the scriptimmend ```setTimeMultiplier```

However, i'm not sure if this really requires a parameter. Shouldn't the mission maker decide/set the speed in which his mission passes time?

**Comment by Pasrules** [comment]
Good point, this doesn't require a parameter.
