### ISSUE TITLE
TFR bug, possible

### ISSUE THREAD

**Issue by Przemro** [ferstaberinde/F3#690]
In our version of F3 we had problem with TFR and it looks like here it is too. You can t change radio to speakers, for us we fix it by change in: f/radios/tfr/fn_tfr_setRadioFrequencies.sqf

`tf_freq_west =    [0 ,7, ["31","32","33","34","35","36","37","38","39"],0, nil, -1, 0, getPlayerUID player, false];
tf_freq_west_lr = [3 ,7, ["51","52","53","54","55","56","57","58","59"],0, nil, -1, 0, false];
tf_freq_east  =   [0 ,7, ["31","32","33","34","35","36","37","38","39"],0, nil, -1, 0, getPlayerUID player, false];
tf_freq_east_lr = [3 ,7, ["51","52","53","54","55","56","57","58","59"],0, nil, -1, 0, false];
tf_freq_guer  =   [0 ,7, ["31","32","33","34","35","36","37","38","39"],0, nil, -1, 0, getPlayerUID player, false];
tf_freq_guer_lr = [3 ,7, ["51","52","53","54","55","56","57","58","59"],0, nil, -1, 0, false];`

**Comment by Pasrules** [comment]
@Przemro  "You can't change radio to speakers", could you please clarify what you mean please.

**Comment by Przemro** [comment]
TFR have option to turn on speakers, so people around you can hear your radio. Example, as squad leader you have LR radio and you can turn on speakers so your squad hear what HQ is saying.

You can also turn on speakers, then drop radio somewhere to lure other players into trap, etc.

If speakers are turned off, you use headphones in radio, and nobody around you can hear your radio.

**Comment by Pasrules** [comment]
I'll test this and add it to the PR

**Comment by Pasrules** [comment]
Confirmed and included in PR
