### ISSUE TITLE
F3 Weather: Add new (default) option: "Use mission settings"

### ISSUE THREAD

**Issue by Wolfenswan** [ferstaberinde/F3#691]
If applied, it'll use the values set by the mission-maker in the editor. Given the new, more powerful configuration in the editor itself this can be more user-friendly than fiddling with the script files.

**Comment by jameslkingsley** [comment]
:thumbsup:

**Comment by Khaosmatic** [comment]
This will be a big help!

**Comment by Wolfenswan** [comment]
Closing as PR has been merged into dev.
