### ISSUE TITLE
Weapons in Vehicles Bug

### ISSUE THREAD

**Issue by Pasrules** [ferstaberinde/F3#692]
Weapons in vehicles placed by assignGear are invisible to some players. Possible only after respawn or resloting after death. All other items/magazines are visible. I say visible because nonkilled players can see them,

**Comment by Wolfenswan** [comment]
Any good reproduction for this?

**Comment by Pasrules** [comment]
There is no error, I made a mistake with the loadout. And i was so sure of it back in November at least it doesn't need fixing.
