### ISSUE TITLE
[Renamed] Remove pre-mount modules

### ISSUE THREAD

**Issue by ted42** [ferstaberinde/F3#696]
I think the PreMount Component might/could be obsolete now, because with the eden editor it's now possible to do the same. (Or roughly the same?)

There might be some other components as well that could be dropped, but I didn't find anything else yet.

**Comment by Khaosmatic** [comment]
What about the new Eden spectator, is that natively supported via a template or is that something F3 needs to actually have set up to run it?

**Comment by thedd** [comment]
The Eden spectator script isn't as feature rich as the one in f3. So I'd definitely keep that one.

**Comment by Khaosmatic** [comment]
Does the f3 spectator support ACRE2 and locational chat? e.g. fly next to a player in spectator and you can hear them while being able to talk to everyone who is dead/in spectator.

**Comment by jameslkingsley** [comment]
@Khaosmatic Yes it does. And the Eden spectator is pretty bad imo..

**Comment by Khaosmatic** [comment]
Awesome, I didn't think it could. That clears up alot of additional scripts I was using alongside F3. It doesn't any setup does it? (Besides setting ACRE as the radio's to use)

**Comment by jameslkingsley** [comment]
Nope. If you look in fn_CamInit.sqf it has `[true] call acre_api_fnc_setSpectator;` which puts the client in and out of spectator mode for ACRE.

**Comment by Khaosmatic** [comment]
Indeed it does work wonderfully!

**Comment by jameslkingsley** [comment]
It's also quite good to use when in Zeus. Does the same thing and lets you hear players on the ground from the perspective of the Zeus camera.

**Comment by Wolfenswan** [comment]
PreMount doesn't work as intended (using the module-sync) due to changes in the init order with 3den. It's slightly more flexible than the in-3den method as it does account for units not being present. E.g. if you dedicated Unit-A as driver in 3den and he isn't slotted you won't have a driver. F3 preMount will move the next unit into the driver slot.

I'd tend to keep it in the files but remove the modules.

What can go however is UAV recharge, BI fixed the related issue a good while ago.

**Comment by ninjaProtocol** [comment]
It does work if you call it from init.sqf, so the calls to the function could go into a separate sqf that can be called from a line in init.sqf.

For example:
`[synchronizedObjects F3_preMount_NATO,["GrpNATO_ASL","GrpNATO_A1","GrpNATO_A2"],false,false] call f_fnc_mountGroups;`
could go into `f\preMount\fn_callMountGroup.sqf`, and from init.sqf one may simply uncomment the line `[] execVM "fn_callMountGroup.sqf"`. Could leave the corresponding game logics as they are, but without init code.

Of course, you'll need a sort of template in the script that lets users choose what and who they want to pre-mount. For an example of such a template, see attached file.
[premount_template_example.txt](https://github.com/ferstaberinde/F3/files/316859/premount_template_example.txt)

**Comment by ferstaberinde** [comment]
I think the best judge of this issue (removal of the preMount component) is @Wolfenswan. I'm happy with complete removal or just removing the modules, though my gut says the latter is a better idea (particularly if we can update the wiki page to help MMs know how to use this going forward).

**Comment by Wolfenswan** [comment]
I agree that keeping a "legacy" version of component seems like the better option.
