### ISSUE TITLE
Unknown Errors [Question]

### ISSUE THREAD

**Issue by Khaosmatic** [ferstaberinde/F3#697]
Hi gents, I've began doing F3 again after some time and started using an old template I made with various faction gear, etc. This version hasn't been used since I think before ARMA version 1.54 and I've had these 3 errors show up and I'm not entirely sure what they full relate to, I understand one is to do with a unit's backpack but I've looked at it and the original code seems fine.

Any assistance would be greatly appreciated!

http://imgur.com/a/qiIBv

**Comment by Khaosmatic** [comment]
If there are any answers then it would be interesting to know what caused it but I have now started anew for the sake of other features, etc that were in a newer F3 version.

**Comment by cptnnick** [comment]
Did you modify assignGear yourself? I see variable names not present in the
default assignGear.

**Comment by Khaosmatic** [comment]
Yes I have been editing it to have certain modded gear and I've noticed that the RAT magazine issue is still present.

**Comment by Khaosmatic** [comment]
*Hangs head in shame*

I miss-typed the assign name for the rifle magazine. Woops! It is all working now. 

One final thing I was planning on making another ticket for it but I don't want to clog up the 'Closed' section, is it possible to do attachments for a launcher? Such as TF47's SMAW with a scope?

**Comment by cptnnick** [comment]
_unit addSecondaryWeaponItem "className"

**Comment by Khaosmatic** [comment]
Doesn't SecondaryWeaponItem only apply to pistols?

**Comment by cptnnick** [comment]
A pistol is a handgun.

**Comment by Khaosmatic** [comment]
Cptnnick you are hero of Soviet Union!

Thanks for the help man.
