### ISSUE TITLE
RHS Vehicle Faction Setting [Question]

### ISSUE THREAD

**Issue by Khaosmatic** [ferstaberinde/F3#698]
Quite a long time ago I put up a question regarding how RHS Vehicles were not accepting custom assigngear and were being reset to default and I was given a line of code to define the vehicle as BLUFOR but in my efforts I have been unable to find reference anywhere for that line.

Is it possible for one of you fine F3 gentleman to point me in the right direction?

Many thanks.

**Comment by cptnnick** [comment]
Check the wiki page on assignGear. The third parameter is optional and
accepts a faction string.

**Comment by Khaosmatic** [comment]
Great it's working! Is that due to RHS not config'ing the vehicles to be recognized as BLUFOR? If it's a genuine issue I'll go ahead at put it on their bugtracker (unless it intentional)

**Comment by cptnnick** [comment]
It's intentional. The RHS factions are not the same as the vanilla factiond.

**Comment by Khaosmatic** [comment]
The more you know.
