### ISSUE TITLE
Respawns + Spectator [Question]

### ISSUE THREAD

**Issue by Khaosmatic** [ferstaberinde/F3#699]
So I have recently been trying to to a RE/JIP / Reinforcement system where once you die you enter spectator but you can quit back to the lobby and then join the same slot to respawn back at base (or in JIP case just spawn at base after mission commence) however I've been having some issues.

1) The spectator doesn't launch when respawns are enabled, my current setting are: 
disabledAI = 1;
respawn = 3;
respawndelay = 999999
respawnOnStart = 0;
respawnTemplates[] = {"Seagull","f_Spectator"};

2) AssignGear doesn't give the gear default class gear, e.g. FTL, I assume because it does it on mission start?

**Comment by Khaosmatic** [comment]
Just had a thought, if you respawned with the default assigngear and group would that then remove the group marker from those still alive? Is that why Folks uses a REJIP Fireteam??

**Comment by Khaosmatic** [comment]
Scratch what I said about testing, I was able to quickly do it however:

- The slot the reconnecting player joined back in was removed?
- The assigngear didn't occur upon respawn (I'm guessing because it does it on server start?)

**Comment by jameslkingsley** [comment]
I've got a heavily modified version of F3 so I probably won't be able to give you direct code, but it's possible to have a respawn button in the spectator to re-create the unit with the correct loadout, move the spectating player into the unit and then re-initialize some stuff. It's take some work though; lots of testing...

**Comment by Pasrules** [comment]
I fixed your problem number 2 in here #688 (JIP Radio Fix) however we may be overhauling JIP so i removed it from the PR. You have to use the role selector for your loadout tho, I would like an option to bypass this in params, maybe i'll look into it if we want that so role is locked after respawn.

**Comment by Khaosmatic** [comment]
Has F3 halted development for the time being regarding the next version? I haven't seen much activity on the Git here.

**Comment by Wolfenswan** [comment]
Most of us are busy with other projects. Also the introduction of 3den poses the question whether F3's model is still adequate.

I've never ever used respawn in one of my missions so I can't really help you there.

**Comment by ferstaberinde** [comment]
@Khaosmatic - development has restarted, but the next release (v3-4-0) will be focused on fixes and the Apex content; leaving this open for now.

**Comment by Przemro** [comment]
I do have working spectator with respawn, but there are quite few problem (it is not working well, 80% time after respawn TFR is broken etc.)
