### ISSUE TITLE
Improving safestart

### ISSUE THREAD

**Issue by Poulern** [ferstaberinde/F3#700]
Right now, while bullets don't leave your gun, and grenades disappear when you throw them. However in PA we're having issues still with the fact that people are trying to test the boundaries with dry firing their guns, backblast(Ace) killing people, trying to be as obnoxious as possible. While i feel that its a community issue i think if safestart could prevent people from firing their guns, period(akin to ace safety), then that would be even better.  

If you guys know how to just do this via ACE as well, I could just integrate that into our framework. Cheers!

**Comment by cptnnick** [comment]
Try using this function

https://github.com/acemod/ACE3/blob/master/addons/safemode/functions/fnc_lockSafety.sqf
