### ISSUE TITLE
[Questions] Removing SMS, random weapon attachments per class.

### ISSUE THREAD

**Issue by Khaosmatic** [ferstaberinde/F3#701]
Another question, I am in the process of removing all the parts of F3 that I do not need such as the Simple Medical System. I have trawled through all files with Notepad++ and cannot find what is calling the script here: http://imgur.com/G3BNzRm

No files say anywhere anything about needing the file located there that I can work out. Does anyone have any idea where that file is being called from?

**Comment by Khaosmatic** [comment]
Another sidequestion unrelated to the launchers, I am in the process of removing all the parts of F3 that I do not need such as the Simple Medical System. I have trawled through all files with Notepad++ and cannot find what is calling the script here: http://imgur.com/G3BNzRm

No files say anywhere anything about needing the file located there that I can work out. Does anyone have any idea where that file is being called from?

**Comment by Wolfenswan** [comment]
Did you remove the entries from cfgFunctions in description.ext?
