### ISSUE TITLE
Add new insignia files for Apex factions

### ISSUE THREAD

**Issue by ferstaberinde** [ferstaberinde/F3#709]
More details when the units are there to play with properly ...

**Comment by ferstaberinde** [comment]
When Carson creates the uniforms for Syndikat I'm going to test and see if any of the existing insignia graphics can be re-used (as we did with NATO insignia on FIA uniforms).

**Comment by ferstaberinde** [comment]
Update: looks like the Syndikat uniforms don't have insignia slots, but I will move on to looking at whether or not we need new artwork for the NATO and CSAT pacific uniforms.

**Comment by ferstaberinde** [comment]
Couple of thoughts after looking at this:

- We need to make new artwork for the NATO and CSAT tropical uniforms
- Currently the insignia file works by sniffing the unit faction, but that's going to cause issues if people use the pre-placed units; so what I would like to do for NATO and CSAT (if possible) is:
-- Move the insignia call to the very end of fn_assignGear
-- Sniff for the unit's uniform from an array of possibles, and then run the appropriate block of code
-- Default to a particular block if the script encounters some other uniform

**Comment by GeEom** [comment]
See below potential recolours for NATO Pacific and CSAT Pacific insignias. The gist is that CSAT use patterned three colour, whilst NATO are more muddy and homogeneous.

![apex insignia sample 01](https://cloud.githubusercontent.com/assets/4153294/16356537/3e9b3c6c-3ad3-11e6-8d48-f1b85814813e.png)

All feedback very welcome!

**Comment by GeEom** [comment]
Attached: PNGs and PAAs for each pacific insignia. CSATP sandier than previewed above.

[Pacific insignias.zip](https://github.com/ferstaberinde/F3/files/333061/Pacific.insignias.zip)

**Comment by GeEom** [comment]
and source psds

[insignia psds.zip](https://github.com/ferstaberinde/F3/files/333074/insignia.psds.zip)

**Comment by ferstaberinde** [comment]
Thanks to @GeEom we now have Pacific variants of the NATO and CSAT insignias, plus a revised script that will allow the mission maker to select the variant to use (on a per faction basis). However, I can't work out how to apply the variants to the medic badges - I think I'm getting the syntax wrong somehow so have commented out my attempt. When @Wolfenswan returns perhaps he can help?

**Comment by ferstaberinde** [comment]
Thanks to @headswe the issue with the medic badges is resolved. Closing!
