### ISSUE TITLE
Move vehicle crews into vehicles

### ISSUE THREAD

**Issue by Wolfenswan** [ferstaberinde/F3#712]
Currently all vehicle crews are assigned using the ```this moveInDriver VehName``` (or inGunner etc) line in their init field. This is no longer required and it would be cleaner to simply place them in their vehicles in the editor and remove the lines in the init fields.

**Comment by ninjaProtocol** [comment]
I had a go at this, here's the resulting branch:
https://github.com/ninjaProtocol/F3/tree/issue-712
