### ISSUE TITLE
Use setUnitTrait for vehicle crew to allow vehicle repair

### ISSUE THREAD

**Issue by Wolfenswan** [ferstaberinde/F3#713]
Currently vehicle drivers are "repair specialists" with crew gear assigned. 

Using ```this setUnitTrait ["engineer",true]``` in a unit's init line it can be given the ability to repair. Thus all vehicle crews could be given the ability to repair. A repair kit could be added by default or still restricted to the crew chief.

**Comment by Wolfenswan** [comment]
This could also be used in the assignGear files. E.g. the medic loadout could always set the "medic" 'trait' to true and the crew chief loadout always give the engineer trait to the unit it is applied to.

**Comment by Wolfenswan** [comment]
As per chat we've agreed on adding this to assignGear once the major work on the component is done. Classes it would be applied to:
* Vehicle driver ("vd")
* Crew chiev ("pcc")

What about regular pilot/co-pilot ("pp"), regular helicopter crew ("pc") and vehicle commanders/gunners?

**Comment by ferstaberinde** [comment]
I agree with your proposal (PP, PCC and VD only) and have implemented it. Closing.
