### ISSUE TITLE
Merging vehicle/crate assignGear into one file

### ISSUE THREAD

**Issue by Wolfenswan** [ferstaberinde/F3#718]
Currently the crate & vehicle loading in each assignGear file takes up 128 lines in each file Technically they are all identical.

My suggestion is to move them into a single file ('f_assignGear_vehicles.sqf') and #include it in the assignGear for each faction. If a mission maker needs different vehicle loadouts for each faction it's easy to copy and paste them back into the file or tweak it otherwise. @pasrules class additions made in #689 could be included. 

Alternatively @pasrules method in #689 could be used and use a 'assignGear_faction_v.sqf' file for each faction.

**Comment by ferstaberinde** [comment]
@Wolfenswan - I'm not sure I'm seeing a massive problem with the duplication: you could probably optimise the gear scripts in many ways, but it would then be harder for newbie MMs to edit. 

If we did combine the crate and vic blocks into a single - shared - include file, do you think we would run into issues with vics from different factions having different cargo capacities?

Alternatively, if we went with @Pasrules proposal for separate files per faction, is the main benefit making it easy for the MM to get to those blocks (by opening a small file, not scrolling down the very long gear files)?

**Comment by Wolfenswan** [comment]
> If we did combine the crate and vic blocks into a single - shared - include file, do you think we would run into issues with vics from different factions having different cargo capacities?

We're not maxing them out currently and iirc A3 "overloads" the vehicles if gear is assigned via script.

> Alternatively, if we went with @Pasrules proposal for separate files per faction, is the main benefit making it easy for the MM to get to those blocks (by opening a small file, not scrolling down the very long gear files)?

It would reduce bloat in the main assignGear file and imho make it easier to parse.

**Comment by Pasrules** [comment]
Ill separate the gear files then make vehicle additions for easy reference.
Vehicles will be the same as #689 i.e tank, helo_(h,m,l)

This issue will be closed on pull submission unless further discussion arises.

**Comment by Pasrules** [comment]
#730
