### ISSUE TITLE
Changes to mission conditions

### ISSUE THREAD

**Issue by darkChozo** [ferstaberinde/F3#719]
A few issues here, in order of priority -

The current time of day presets don't work in Tanoa, most likely because the seasons are reversed compared to Altis. Sunrise is at ~6:30 and sunset is at 18:30, which means that the Dawn, Early Morning, Evening and Dusk presets are all during the night. We might want to set these times dynamically; see BIS_fnc_sunriseSunsetTime.

The current weather presets are fairly lacking. There are currently four; Clear, Overcast, Rain, and Storm (which is essentially Rain with high wind and lightning). Most have no/light/strong wind options, which has very little impact in vanilla. I'd like to see less wind options and more general weather options; for example, something like Clear, Cloudy, Overcast, Foggy, Light Rain, Rain, Thunderstorm.

Currently, fog is set separately from weather. IMO the weather param should set fog as well, and then the fog param can be used to override the weather param if the host desires (ie. Rain could set a very light fog, which the host could optionally override using the fog param). Wind could be handled similarly.

Finally, it would be nice if there was a way to set weather forecast using parameters. For example, if you wanted to have a storm roll in during a mission, there's currently no way to do so using default F3. This might be too feature-creepy, however.

**Comment by ferstaberinde** [comment]
@darkChozo - the issue of TOD presets not working means we have to address this component in some way as part of v3-4-0, so I'm adding it to the milestone and assigning it to you.

I think forecasting is feature-creep at this stage, and whatever we do we should retain the 'use mission conditions' option that @Wolfenswan has added in a recent PR. However, if you'd like to set out (here) the parameters and options you propose for the revised version that would be great. Personally, I really like your ideas for more general weather options (and treating the fog and wind parameters more like 'overrides') - it actually makes more sense from a simulation POV.

**Comment by darkChozo** [comment]
What I'm envisioning is something like this - 

Weather (approximately):
- Use mission conditions
- Clear (no clouds, no rain, no fog, no wind)
- Cloudy (50% clouds, no rain, no fog, light wind)
- Overcast (100% clouds, no rain, no fog, light wind)
- Foggy (100% clouds, no rain, 20% fog, light wind)
- Light Rain (100% clouds, 10% rain, 5% fog, light wind, rainbows?)
- Rain (100% clouds, 75% rain, 15% fog, medium wind)
- Storm (100% clouds (I wish there were stormclouds...), 100% rain, 20% fog, high wind, lightning)

That's an initial smattering, you could also go on with things like Mostly Cloudy (70% clouds, move cloudy to 30%), Heavy Fog (50% fog?), Showers (10% rain, 50% clouds), and so on.

Fog and Wind should probably be Override Fog/Wind, with these options:
- Don't override
- No Fog/Wind
- Light Fog/Wind
- Heavy Fog/Wind

**Comment by ferstaberinde** [comment]
That looks great. Can you have a go at creating some code? BTW, did you see my comments about some of the rationale behind how things get scripted in F3 (posted to the Discord channel). Just please bear that in mind.
