### ISSUE TITLE
Minor Pre-release Work

### ISSUE THREAD

**Issue by Wolfenswan** [ferstaberinde/F3#727]
List of things that need to be done before the release but don't warrant their own issue. I'll add things to the list as they arise. These should be done when all other issues are finished.

- [x] Decide on whether to keep or remove group ID component (related to A3 bug https://feedback.bistudio.com/T118543)
- [x] Removal of legacy/commented components (groupMarker/groupID related)
- [x]  Removal of extra batteries in assignGear files (uavCharge Component)
- [x] Make sure unit order in slotting screen is correct
- [x] Change "Repair Specialist" Units to Pilot and Crew (no longer required due to #713)
- [x] Check that the 'Use mission settings' commit that was made to MASTER won't cause a problem (it may have been dealt with by @Wolfenswan already): https://github.com/ferstaberinde/F3/commit/acb989c825829de978e5ff740f0aeba99b7f9994
- [X] Remove duplicate GPS in assignGear (e.g. CO & Vehicle Driver get a GPS when it's already linked to all units prior)
- [x] Remove mission header from description.ext (can also be set in the editor now)

Not doing:
- Merge some loadout file into one (FIA & FIAAK, Nato & NatoP, CSAT & CSATP)

**Comment by ferstaberinde** [comment]
Have removed the batteries from the gear loadouts.

**Comment by ninjaProtocol** [comment]
Er... could you add "set default weather in editor to 30% overcast"? :smile: 

Should have just done it myself in the last PR i made, just thought it shouldn't be a change grouped with something completely different to what I was doing.
