### ISSUE TITLE
Fixing Transfer of Group Leadership

### ISSUE THREAD

**Issue by ninjaProtocol** [ferstaberinde/F3#737]
Often when a group leader dies, leadership is incorrectly transferred (i.e. not according to the ORBAT). This may cause confusion among those relying on methods like STHud, or any other indication of leadership (even default group icons would be transferred to the next misconfigured leader and not the actual leader).

Simple fix is to correctly change the ranks of all player units. By default, all units with the same rank are next in line for group leader in the order that they are grouped to the leader. This is also the order that should show up in STHud. While this should work most of the time, it sometimes goes wonky (not really sure why, maybe something changed in the group order for some groups). Setting ranks overrides this behaviour and makes it more explicit.

Setting ranks with respect to other groups should also ensure smooth leadership transitions with adhoc/merged groups formed when losses have become high (couldn't test this on my own).

Current ranks from highest to lowest are:

7 - Colonel
6 - Major
5 - Captain
4 - Lieutenant
3 - Sergeant
2 - Corporal
1 - Private

_Current rank assignment:_

**CO/DC Group**
CO - 4
DC - 3
JTAC - 3/2/1 depending on faction (inconsistent?)
UAV Operator - 2/1 depending on faction (inconsistent?)
Medic - 1

**SL Group**
SL - 3
Medic - 1

**Fire Team**
FTL - 2
Rest of FT - 1

**Vehicle**
VC - 3
G - 2
D - 1

**Helicopters**
P - 5
CP -4
G1 - 3
G2 - 2

_Suggested assignment:_

**CO/DC Group**
CO - 7
DC - 6
JTAC - 2
UAV - 1
Medic - 1

**SL Group**
SL - 5
Medic - 1

**Fire Team**
FTL - 4
ARs - 3
R(AT) - 2
Rs - 1

**Vehicle**
Can be left as is

**Helicopters**
Can be left as is, if they're supposed to be at par with SLs, otherwise bump them down by a rank:
P - 4
CP -3
G1 - 2
G2 - 1

**Comment by ferstaberinde** [comment]
This is an excellent idea - and thank you for laying out the rationale and plan so clearly. Let's make this part of v3-4-0. I will also help (we'll need to co-ordinate our work carefully).
