### ISSUE TITLE
Add new units and factions to assignGearAI

### ISSUE THREAD

**Issue by darkChozo** [ferstaberinde/F3#740]
Several of the new units, mostly the Syndikat ones, have classnames that don't fit the existing naming scheme. That means that assignGearAI will make them riflemen by default. Also, that's not actually true because assignGearAI needs to be changed to acknoledge the new factions.

Factions that have to be added - NATO Pacific, CSAT Pacific, CTRG, Syndikat. Gendarmie wouldn't work unless we give them a specific assignGear file so probably best to leave them off.

Units that need to be added - 

Bandit_1 + Para_3 (medic)
Bandit_2 + Para_5 (rat)
Bandit_3 + Para_4 (ar)
Bandit_4 + Para_2 (ftl)
Bandit_5 + Para_1 (heavier rifleman)
Bandit_6 + Para_6 (grenadier)
Bandit_7 + Para_7 (lighter rifleman, probably carabiner?)
Bandit_8 (eng mines)
Para_8 (eng explosives)
JTAC (duh)

Also, if there's anything else we're missing now would be the time to add them.

**Comment by Wolfenswan** [comment]
I wonder if it would make more sense to change the factions array to an *exclude*, i.e. to specify the factions which should not be affected.
