### ISSUE TITLE
Add APEX factions to components where relevant

### ISSUE THREAD

**Issue by Wolfenswan** [ferstaberinde/F3#745]
New factions need to be included (if only as a dummy file or redirecting to the files of an existing faction) in
- briefing
- group markers
- assignGear
- groupID (only where applicable)

The factions are:
- [x] NATO (P)
  - [x] briefing
  - [x] group markers
  - [x] assignGear
  - [x] group ID

- [x] CSAT (P)
  - [x] briefing
  - [x] group markers
  - [x] assignGear
  - [x] group ID

- [x] CTRG
  - [x] briefing
  - [x] group markers
  - [ ] assignGear
  - [x] group ID

- [x] Syndikat
  - [x] briefing
  - [x] group markers
  - [x] assignGear
  - [x] group ID

**Comment by ferstaberinde** [comment]
Have ticked the briefing check-boxes for NATO (P), CSAT (P); but I am not sure we will need group markers or group ID for CTRG. I'm also not sure we need to make provision for the Gendermerie in this release.

**Comment by Wolfenswan** [comment]
CTRG should at least be recognized. They could possibly be added to the arrays for NATO & FIA so they can see either by default.
