### ISSUE TITLE
Minor assignGear errors

### ISSUE THREAD

**Issue by Ferrard** [ferstaberinde/F3#769]
1. FIA (Altis) loadouts are not randomly selecting between TRG-20/21 and Mk.20/20C rifles
2. _pistolmag loads in after _pistol, resulting in unloaded pistols
3. UGL smoke rounds loads in after _glrifle, resulting in unloaded CO and JTAC/FAC UGLs
4. Medium SAM's _SAMmag loads in after _SAM, resulting in unloaded Titan AA Launcher
5. CTRG does not declare or define variables for _MAT, _MATmag1, or _MATmag2
6. CTRG Medium AT Team are getting _RAT and _RATmag on "Light" loadout instead of _MAT and _MATmag1
7. CTRG and Syndikat Medium SAM Team are receiving _HAT instead of _SAM

Fixes in progress.

**Comment by Ferrard** [comment]
5. CTRG Medium SAM Team receiving _HAT instead of _SAM

**Comment by Ferrard** [comment]
Fixed files at the Google Drive folder below. I'm not sure how to <verb> them up to GitHub so that this can be <2nd verb>ed into F3.

https://drive.google.com/open?id=0B4zOocojp0NxTEVxaVVWQnFtTFk

**Comment by Wolfenswan** [comment]
"uav" class needs to use
```_unit linkItem _uavterminal```

**Comment by Wolfenswan** [comment]
I'd suggest chancing the _satchel to "DemoCharge_Remote_Mag".
Currently it's "SatchelCharge_Remote_Mag" which weighs 60 more and is generally overkill.

**Comment by Ferrard** [comment]
Good catch re: UAV. Re: satchel, the weight is fine with me. Given the number of objective-ish items out there that take a ridiculous number of demo-charges to destroy (think the Tanks from _Bees_), I like using single big booms instead of multiple, anti-climactic little booms that we invariably underestimate the power of. It's just a more satisfying player experience to me.

**Comment by Wolfenswan** [comment]
I noticed the _satchel is inconsistent through factions. E.g. AAF still uses Democharge.

Suggestion: Add _democharge.

**Comment by Ferrard** [comment]
Hmm... you are correct, _satchel was incorrectly defined for just about everyone. After work I'll correct so that there's both _satchel and _democharge.

**Comment by Ferrard** [comment]
- UAV is now correctly using linkItem
- _satchel now refers to SatchelCharge_Remote_Mag for everyone
- Added _democharge referring to DemoCharge_Remote_Mag

Dinnering now. Will attempt to [gitverb] a [gitnoun] afterwards!

**Comment by Ferrard** [comment]
I have failed at [gitverb]ing. In lieu of a successful [gitverb], I offer a Google Drive hosted .zip file for anyone who wants to [gitverb] these updated files for me. This covers everything noted in Issues 769 and 770

https://drive.google.com/open?id=0B4zOocojp0NxQlBRdUpNR1F1enc
