### ISSUE TITLE
Docu for v3-4-1

### ISSUE THREAD

**Issue by ferstaberinde** [ferstaberinde/F3#771]
* Added F3 Gendarmerie component, with support for this added to:
  * Briefing Template component.
  * F3 Folk ARPS Assign Gear Script component.
  * F3 Folk ARPS Group Markers component.
  * F3 Folk ARPS Group IDs component.
* Updated F3 Folk ARPS Assign Gear Script component:
  * Various minor fixes.
* Updated F3 Folk ARPS Platoons component:
  * Fixed issues with order of Syndikat slots.
* Updated Insignia component:
  * Automatically supports mission-maker placed Pacific units (NATO and CSAT).
* Updated Mission Header component documentation.

++

- [x] Update Insignia page
- [x] Update Briefing page
- [x] Update Assign Gear page
- [x] Create Gendarmerie page
- [x] Update Mission header page

**Comment by ted42** [comment]
"Mission Header" docu page needs to be completely rewritten, since it's all in the eden editor now.
